### ISSUE TITLE
MSI applications

### ISSUE THREAD

**Issue by rovabu** [microsoftgraph/powershell-intune-samples#1]
Hello,

Do you already have samples to add a MSI into the Intune Service that you have authenticated with?

**Comment by lleonard-msft** [comment]
@rovabu - There's an open request to add an appropriate sample; I'm afraid I don't have more specific information.  I will update the issue if/when more info is available.

**Comment by slaet** [comment]
I think this should work for rovabu: https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/intune_apps_windowsmobilemsi
