### ISSUE TITLE
No unattended samples

### ISSUE THREAD

**Issue by clickbangdead** [microsoftgraph/powershell-intune-samples#10]
All these samples are for manual execution, when can we see samples suitable for automation? I've yet to find a good way to setup a script to run as a scheduled task or SCORCH process because the authentication requirements are onerous (i.e., requiring typing into a authorization web form, or doing admin consent again through a webform instead of just pre-provisioning permissions to service accounts). Are we likely to see good documentation related to this anytime soon?

**Comment by davefalkus** [comment]
Hi there,

Have you reviewed our authentication section which shows auth from file?
https://github.com/microsoftgraph/powershell-intune-samples/tree/master/Authentication

Let us know if there isn't enough information.

Dave

**Comment by clickbangdead** [comment]
I had played around with something similar, but I keep running into this:
Cannot convert argument "ctx", with value: "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext", for "AcquireTokenAsync" to type "Microsoft
.IdentityModel.Clients.ActiveDirectory.AuthenticationContext": "Cannot convert the "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" val
ue of type "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" to type "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationCont
ext"."

I've got version 2.0.0.131 of the AzureAD modules installed, and I verified that it's actually grabbing those dlls:
C:\Program Files\WindowsPowerShell\Modules\AzureAD\2.0.0.131\Microsoft.IdentityModel.Clients.ActiveDirectory.dll
C:\Program Files\WindowsPowerShell\Modules\AzureAD\2.0.0.131\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll

**Comment by davefalkus** [comment]
When you load your PowerShell session are you loading the MSOnline module? 

We see the error your getting when you have connected with "Connect-MsolService" or ran "Import-Module MSOnline" and then try to run an Intune sample from GitHub. The reason for the error is that the ADAL modules are different major versions.

If you check the loaded modules when you have run "Connect-MsolService" or "Import-Module MSOnline" you will see it loads ADAL version 2.26.0.0.

ADAL version 2.26.0.0 loaded from:
'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\MSOnline\Microsoft.IdentityModel.Clients.ActiveDirectory.dll'.

Major  Minor  Build  Revision
2          26       0        0

If you haven't loaded the "MSOnline" module when you start your session and run one of the samples the loaded ADAL module will be major version 3 and different path to the dll.

ADAL version 3.13.9.1126 loaded from:
'C:\Program Files\WindowsPowerShell\Modules\AzureAD\2.0.0.131\Microsoft.IdentityModel.Clients.ActiveDirectory.dll'.

Major  Minor  Build  Revision
3          13       9         1126

The reason why it fails with v2 is that it calls "AcquireTokenAsync" which isn't part of the v2 MSOnline module, it only has AcquireToken.

When you start your PowerShell session are you using the "Microsoft Azure Active Directory Module for Windows PowerShell" or running PowerShell.exe native?

If you check the "Microsoft Azure Active Directory Module for Windows PowerShell" shortcut you can see below that it runs a command by default to import the module MSOnline which will cause the error your seeing.

C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe  -NoExit -Command "Import-Module MSOnline"

Hope this helps and explains what's happening, could you try a PowerShell session without loading the MSOnline module and let us know the result?

Thanks

Dave

**Comment by clickbangdead** [comment]
So that was definitely it, I removed the old msol modules and restarted, no longer getting the ctx error. had another issue because the command doesn't return any errors even when there is one unless you remove the ".result". Now I just have to figure out how to grant admin consent to this service account, so far I've granted it like three times but apparently it never sticks. Permissions in Graph are a complete mess compared to other systems I've managed, no simple console or set of powershell commands to just simply grant the user the required permissions.

Thank you for your assistance.

**Comment by davefalkus** [comment]
We have an admin_consent script coming to this GitHub repository so you can set it on behalf of the application (Note: Only a Global Admin can run this). 

From there the users but in your case the service account permissions / role will be used to what they can do e.g. If you create an Intune Role to only allow a set of users to read Intune components that's all they will be able to do via a Graph call, if they tried an add or delete policy it would be blocked.

We have documentation on the permissions below:
https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference 

Hope this help and any further questions let us know and thanks for the feedback.

Dave

**Comment by clickbangdead** [comment]
Is there a console somewhere to assign those graph permissions to a user? I've only see where you can assign to an app you register, nowhere to add them to a user. I did make the service account an Intune Administrator, but that didn't help.

**Comment by mihaiLucian** [comment]
Hello,

At this moment I don't believe is such a place. 
Below is a UI to try all the graph querries. On the left side you have sign in with Microsoft button. There you can assign permissions for the user that you used to log in.

https://developer.microsoft.com/en-us/graph/graph-explorer

Hope that helps. I

**Comment by clickbangdead** [comment]
So the issue there is no matter how many times I consent in the Graph Explorer, it never actually assigns the permission to the service account. I've never gotten that to work, sometimes the site just errors out, other times it says "all good" but the permissions aren't there. The whole admin consent flow seems to be both very broken and completely unintuitive. it just seems silly that there is not a simple console or set of powershell commands to explicitly assign the graph permissions to a user account or group, everything is setup for manual logins with the end user granting their permission. That's fine and dandy for consumer apps, but completely backwards to how an organization wants to manage permissions.

**Comment by clickbangdead** [comment]
So, hate bringing this up again, but do we have a solution for unattended script execution? Still need a way to run reports against Intune Graph in an automated, unattended way, but EVERYTHING I've seen or tried has required admin consent at some point, which means a GUI, which precludes running in a scheduled task or SCORCH. There seems to be no way to grant the Graph permissions to a service account that I can find. The only way I've even gotten my service account (which is both licensed and IN the Intune Admin role) to ever get access was to admin consent through the GUI using my global admin credentials. And that consent never stuck around, so I had to keep doing it. I just need to be able to pull live data in a scheduled, reliable way with no user interaction.

**Comment by davefalkus** [comment]
For the PowerShell script samples we are going to upload a script to set admin consent by a Global Admin for your tenant so the functionality you expect will work, note: the script is not for Graph Explorer.

From an zero touch automation we have the following sample already in the repo:
https://github.com/microsoftgraph/powershell-intune-samples/blob/master/Authentication/Auth_From_File.ps1

For reporting have you also looked at the Intune Data Warehouse?
https://docs.microsoft.com/en-us/intune/reports-nav-create-intune-reports

**Comment by clickbangdead** [comment]
I need to automate reporting into another on premises analytics system on a regular (i.e., several times a day/semi-real-time) basis, so hopefully whenever I get the admin consent script I'll be able to finally assign the permissions to the service account. Additionally, I'd like to do some auto-assignment to device groups based on device properties that are not currently allowed for dynamic grouping (like the osVersion property) and to do so in an automated way as well. There is additional information, especially enhanced device properties that seems to be available only in the data warehouse that I would like to also use, hoping that that information is also exposed via graph and/or dynamic grouping at some point in the future.

As for the data wharehouse itself, I see the utility and think it's a great feature, but right now I have no scripts readily available to automate that either, and I don't want to have to train a bunch of users on PowerBi (which I am still a novice on myself) just to get some nuggets of info in their hands.

**Comment by davefalkus** [comment]
Hi, I've just added the admin consent script to the repo:
https://github.com/microsoftgraph/powershell-intune-samples/tree/master/AdminConsent

From a data warehouse perspective we have a repo for that as well with PS scripts:
https://github.com/Microsoft/Intune-Data-Warehouse/tree/master/Samples/PowerShell 

Let us know if the admin consent addresses your issue.

Thanks

Dave

**Comment by clickbangdead** [comment]
The Admin Consent script looks to have completely corrected the issue, I was able to finally gather the information using the service account.
