### ISSUE TITLE
Upload intunewin file PowerShell GraphAPI

### ISSUE THREAD

**Issue by SimonBuehler3** [microsoftgraph/powershell-intune-samples#104]
Hi

When I create a new win32loeb app with PS and GraphAPI, it creats the app but I can't upload my intunewin file. I'd like to upload my file with the GraphAPI or via Azure portal GUI. 

JSON Body:

        "@odata.type" = "#microsoft.graph.win32LobApp";
        "applicableArchitectures" = "x64";
        "description" = "-";
        "detectionRules" = @(@{
            "@odata.type" = "microsoft.graph.win32LobAppRegistryDetection";
            "check32BitOn64System" = $true;
            "keyPath" = "HKEY_LOCAL_MACHINE\SOFTWARE\MyKey";
            "valueName" = "Status";
            "detectionType" = "string";
            "operator" = "equal";
            "detectionValue" = "Installed"
        });
        "developer" = "ig";
        "displayName" = "MyApp";
        "uploadState" = 0;
        "fileName" = "Mozilla-Firefox.intunewin";
        "installCommandLine" = "Deploy-Application.exe Install";
        "uninstallCommandLine" = "Deploy-Application.exe Uninstall";
        "installExperience" = @{
            "runAsAccount" = "system"
        };
        "informationUrl" = "";
        "isFeatured" = $false;
        "largeIcon" = $null;
        "notes" = "-";
        "minimumSupportedOperatingSystem" = @{
            "v10_1803" = $true
        };
        "msiInformation" = $null;
        "owner" = "";
        "privacyInformationUrl" = "";
        "publisher" = "Mozilla";
        "returnCodes" = @(
            @{"returnCode" = 0;"type" = "success"}
            @{"returnCode" = 1707;"type" = "success"}
            @{"returnCode" = 3010;"type" = "success"}
            @{"returnCode" = 1641;"type" = "hardReboot"}
            @{"returnCode" = 1618;"type" = "retry"}
        );
        "runAs32Bit" = $false;
        "setupFilePath" = "Deploy-Application.exe";
       }

GUI:
(The app package file is grayed out)
![Capture](https://user-images.githubusercontent.com/19424642/60517655-5689f580-9ce0-11e9-8355-4a1db6d3ba4c.PNG)

Can someone help me?
Thanks!!
Cheers
Simon

**Comment by tabs-not-spaces** [comment]
would that not be due to the fact that the sample code actually uploads the *.intunewin file as part of its process? you don't need to manually upload the file if it's already there. or am I missing something?

**Comment by davefalkus** [comment]
As per @tabs-not-spaces , the sample script below does the intunewin upload for you automatically.

https://github.com/microsoftgraph/powershell-intune-samples/blob/master/LOB_Application/Application_LOB_Add.ps1

**Comment by davefalkus** [comment]
Closing the issue, please reopen if sample script doesn't address your issue.

Thanks
Dave
