### ISSUE TITLE
DeviceConfiguration_Export.ps1 does not export device configuration policies of type "Administrative Templates".

### ISSUE THREAD

**Issue by wiseleaf23** [microsoftgraph/powershell-intune-samples#108]
DeviceConfiguration_Export.ps1 does not export device configuration policies of type "Administrative Templates".

**Comment by bbuchan10** [comment]
I am seeing the same thing. Is anyone watching this repo anymore?? There doesn't appear to be an easy way to create policy templates to use across tenants at this point...

**Comment by davefalkus** [comment]
Hi @bbuchan10,

We are still looking after this repo. The export device configuration script exports policies from deviceManagement/deviceConfigurations whilst admin templates are in a different endpoint below.

https://graph.microsoft.com/beta/deviceManagement/groupPolicyConfigurations

That's why the export doesn't export admin templates.

Thanks

Dave

**Comment by bbuchan10** [comment]
Thank you for your reply. Are you planning on releasing a group of powershell scripts for Group Policy Configurations?

**Comment by bbuchan10** [comment]
I did find this repo that has a working ADMX Export script. Very nice and works as expected. https://github.com/sandytsang/MSIntune/tree/master/Intune-PowerShell/DeviceConfiguration

**Comment by SGeeves** [comment]
The above was helpful, however I am struggling with assignments for the ADMX re-import.
Has anyone got anything written to assign a group to the completed import?

**Comment by davefalkus** [comment]
Will look at adding ADMX export and import in a future release

**Comment by chibs89** [comment]
Still badly needed are there any news?

**Comment by SGeeves** [comment]
Function Add-GroupPolicyConfigurationsAssignment(){

<#
.SYNOPSIS
This function is used to assign a group to a group policy configuration using the Graph API REST interface
.DESCRIPTION
The function connects to the Graph API Interface and adds a device compliance policy assignment
.EXAMPLE
Add-GroupPolicyConfigurationsAssignment -GroupPolicyId $GroupPolicyConfigurationID -TargetGroupId $TargetGroupId
Adds a group policy assignment in Intune
.NOTES
NAME: Add-GroupPolicyConfigurationsAssignment
#>

[cmdletbinding()]

param
(
    [Parameter(Mandatory = $false)]
	[string]$GroupPolicyId,
    [Parameter(Mandatory = $true)]
	[string]$TargetGroupId
)

$graphApiVersion = "beta"
$Resource = "deviceManagement/groupPolicyConfigurations/$GroupPolicyId/assign"
    
    try {

$JSON = @"

    {
        "assignments": [
        {
            "target": {
            "@odata.type": "#microsoft.graph.groupAssignmentTarget",
            "groupId": "$TargetGroupId"
            }
        }
        ]
    }
    
"@

    $uri = "https://graph.microsoft.com/$graphApiVersion/$($Resource)"
    Invoke-RestMethod -Uri $uri -ContentType "application/json" -Headers $authToken -Method Post -Body $JSON

    }
    
    catch {

    $ex = $_.Exception
    $errorResponse = $ex.Response.GetResponseStream()
    $reader = New-Object System.IO.StreamReader($errorResponse)
    $reader.BaseStream.Position = 0
    $reader.DiscardBufferedData()
    $responseBody = $reader.ReadToEnd();
    Write-Host "Response content:`n$responseBody" -f Red
    Write-Error "Request to $Uri failed with HTTP Status $($ex.Response.StatusCode) $($ex.Response.StatusDescription)"
    write-host
    break

    }

}
