### ISSUE TITLE
DeviceConfiguration_Export.ps1 also exports "Software update" policies

### ISSUE THREAD

**Issue by wiseleaf23** [microsoftgraph/powershell-intune-samples#109]
DeviceConfiguration_Export.ps1 also exports "Software update" policies. This is also processed by the SoftwareUpdates_Export.ps1 script. I suggest only exporting the "real" device configuration policies and the Sofware update policies in the "SoftwareUpdates_Export.ps1" script.

**Comment by davefalkus** [comment]
Hi @wiseleaf23,

Fixed issue with script update to filter out iOS and Windows Software Update policies, same for SoftwareUpdate_Export script.

https://github.com/microsoftgraph/powershell-intune-samples/blob/master/DeviceConfiguration/DeviceConfiguration_Export.ps1

Thanks for raising it.

Dave
