### ISSUE TITLE
Sync managed devices by 'lastSyncDate' doesn't work

### ISSUE THREAD

**Issue by dmitry-kokora-mc** [microsoftgraph/powershell-intune-samples#11]
In https://github.com/microsoftgraph/powershell-intune-samples/blob/master/CheckStatus/Check_lastSyncDateTime.ps1
you sync devices by 'lastSyncDate' using this URI="https://graph.microsoft.com/beta/managedDevices?`$filter=lastSyncDateTime ge $daysago". 
But the character ` in front of the query parameter does not allow the request to be executed correctly. This query parameter is simply ignored and you always get all the devices.

Using operators 'gt', 'ge' with dates always gives an empty response (((
It looks like at the moment with the dates correctly works only the operator 'lt'.

**Comment by davefalkus** [comment]
Hi Dmitry-kokora-mc,

I've just updated the script as there were some invalid characters if you downloaded the raw script from the UI. 

I did some testing with the script and it doesn't fail for me. Could you provide the environment that your using to see if we can reproduce it, i.e. PowerShell version and Operating System your using and whether your running the script through powershell.exe or powershell_ise.exe?

Also what have you got set for "$days = 30"? Also if you output $uri to screen from line 295 with the ` does it output correctly? If I output $uri to screen the ` is removed.

https://graph.microsoft.com/beta/managedDevices?$filter=lastSyncDateTime ge 2017-08-12T09:20:51Z

You can also take this url and use Graph Explorer to do the same test to confirm functionality.

Let us know.

Dave

**Comment by dmitry-kokora-mc** [comment]
Hi Dave,

thanks for the update. I no longer doubt the correctness of your script.

However, I'm interested in the request that you are performing. I use Postmen or Graph Explorer and for me, for example, your request 'https://graph.microsoft.com/beta/managedDevices?$filter=lastSyncDateTime ge 2017-08-12T09:20:51Z' returns the following:
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#managedDevices",
    "@odata.count": 0,
    "value": []
}
But this is not so. 

But 'https://graph.microsoft.com/beta/managedDevices?$filter=lastSyncDateTime lt 2017-10-12T09:20:51Z' example with the operator 'lt' works out correctly.

I'm confused. And I don't understand why requests can work out differently in our cases. Perhaps you have any assumptions?

Thank you in advance!

Dmitry

**Comment by davefalkus** [comment]
Hi Dmitry,

I've just ran the same query with graph explorer and get the expected 3 devices that haven't synced in the past 30 days with my tenant.

"@odata.context": "https://graph.microsoft.com/beta/$metadata#managedDevices",
    "@odata.count": 3,

The odata.context doesn't show the filter being used, take a look in the link below for "Filter on Complex Type"
http://www.odata.org/getting-started/basic-tutorial/

I will check with our team regarding this and get back to you or you can raise a support ticket from the Portal.

Thanks

Dave
