### ISSUE TITLE
Json import script errors

### ISSUE THREAD

**Issue by Sittampalam** [microsoftgraph/powershell-intune-samples#111]
Hello 
When I try to run the json import script  DeviceConfiguration_Import_FromJSON   I get a series of errors about charcter not supported etc.. and the script does not run. Does it require a particular version of PS? the instruction sgiven does not specify much apart from the path where the json files are.
PS C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM Configuration> .\DeviceConfiguration_Import_Fro
mJSON.ps1

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM
Configuration\DeviceConfiguration_Import_FromJSON.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): R
At C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM
Configuration\DeviceConfiguration_Import_FromJSON.ps1:312 char:159
+ ... TF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM
Configuration\DeviceConfiguration_Import_FromJSON.ps1:351 char:184
+ ... l-rule="evenodd" d="M12 9H7v5H5V9H0V7h5V2h2v5h5v2z"/></svg> <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM
Configuration\DeviceConfiguration_Import_FromJSON.ps1:396 char:238
+ ... ick="Header, go to profile, text:Signed in as">Signed in as <strong c ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM
Configuration\DeviceConfiguration_Import_FromJSON.ps1:425 char:40
+            style="line-height: 20px;" >
+                                        ~
Missing file specification after redirection operator.
At C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM
Configuration\DeviceConfiguration_Import_FromJSON.ps1:431 char:15
+ </summary>    <details-dialog class="details-dialog rounded-1 anim-fa ...
+               ~
The '<' operator is reserved for future use.
At C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM
Configuration\DeviceConfiguration_Import_FromJSON.ps1:613 char:22
+     </option></form><form class ...
+                      ~
The '<' operator is reserved for future use.
At C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM
Configuration\DeviceConfiguration_Import_FromJSON.ps1:618 char:10
+ </form>  </details-menu>
+          ~
The '<' operator is reserved for future use.
At C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM
Configuration\DeviceConfiguration_Import_FromJSON.ps1:640 char:13
+     <main  >
+             ~
Missing file specification after redirection operator.
At C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM
Configuration\DeviceConfiguration_Import_FromJSON.ps1:739 char:231
+ ... TF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM
Configuration\DeviceConfiguration_Import_FromJSON.ps1:741 char:988
+ ... click unstar button, action:blob#show; text:Unstar">        <svg clas ...
+                                                                 ~
The '<' operator is reserved for future use.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

PS C:\source\intune\win10_1703_mdm_configuration\NCSC - Windows 10 - MDM Configuration>

**Comment by davefalkus** [comment]
I've tested the script on github and it worked as expected:
https://github.com/microsoftgraph/powershell-intune-samples/blob/master/DeviceConfiguration/DeviceConfiguration_Import_FromJSON.ps1

How did you download the script? Did you copy the "raw" version from the website?

**Comment by Sittampalam** [comment]
Hello Dave

I right clicked on the file and then save link which save the file to my local drive.  Is there a zipped file with all the scripts that  I can download please?

Nagu Sittampalam
Security Team Leader
Digital and Strategic IT
Southampton City Council
Landline: 02380 833012 | Fax: 02380 832973
e-mail Nagu.Sittampalam@southampton.gov.uk<mailto:Nagu.Sittampalam@southampton.gov.uk>
post Southampton City Council, IT services, 1st Floor, One Guildhall Square, Above Bar, Southampton, SO14  7FP

**Comment by Sittampalam** [comment]
OK I have clicked on raw and then cut and pasted into notepad snd noe the script ran.  I still get an error but I suspect it is syntax.  The file path it is asking should also include the file name as well? I thought it will look in directory and import all the json files there.  What are the created policies called in Intune? I assume it i snot going to interfear with any existing policies and also it is not going to apply to any devices or users?

**Comment by davefalkus** [comment]
The script references using the entire path to a single JSON file:
Please specify a path to a JSON file to import data from e.g. C:\IntuneOutput\Policies\policy.json:

The policies created will be the name from the exported JSON file, you can change the name in the JSON file before importing.

**Comment by Sittampalam** [comment]
Thank you very much for your help. I have imported all the policies now.

Nagu Sittampalam
Security Team Leader
Digital and Strategic IT
Southampton City Council
Landline: 02380 833012 | Fax: 02380 832973
e-mail Nagu.Sittampalam@southampton.gov.uk<mailto:Nagu.Sittampalam@southampton.gov.uk>
post Southampton City Council, IT services, 1st Floor, One Guildhall Square, Above Bar, Southampton, SO14  7FP

**Comment by davefalkus** [comment]
Thanks for the update, will close the issue
