### ISSUE TITLE
Validate-NDESConfig incorrectly reports Unsupported if NDES and CA are in different domains

### ISSUE THREAD

**Issue by russelltomkins** [microsoftgraph/powershell-intune-samples#115]
The Validate-NDESConfig.ps1 script is giving an "Unsupported" error when the NDES Server and Enterprise CA are in different Domains of the same Forest.

Having the NDES server and CA in a different domain **IS** a supported method according to the documentation at [https://docs.microsoft.com/en-us/intune/certificates-scep-configure](https://docs.microsoft.com/en-us/intune/certificates-scep-configure)

> The NDES server must be joined to a domain within the same forest as the Enterprise CA.

Can you advise? The script simply does a name comparison without consideration for the Forest. Is this simply an oversight?.

**Comment by adrian-moore** [comment]
Hi Russel,

Yes, it's an oversight. We'll get it resolved ASAP to ensure the domain is checked across the Forest.

Many thanks for raising this.

Adrian

**Comment by russelltomkins** [comment]
Thanks Adrian for the quick confirmation. This script is such a valuable tool in my NDES / Intune setup checklist.

Russell

**Comment by russelltomkins** [comment]
I use this code to extract all the domains in the forest. Its handy because it gets those few odd setups that also have different domain trees (although thankfully rare) 

`$rootDSE =  [System.DirectoryServices.DirectoryEntry]::New("LDAP://RootDSE")
$directoryEntry = [System.DirectoryServices.DirectoryEntry]::New("LDAP://CN=Partitions,$($rootDSE.configurationNamingContext)")
$searchFilter = [string]"(&(objectClass=crossRef)(systemFlags=3))"
$properties = [String[]]"nETBIOSName","dnsRoot"
$directorySearcher = [System.DirectoryServices.DirectorySearcher]::New($directoryEntry,$searchFilter,$properties)
$searchResults = $directorySearcher.FindAll()
$dnsDomains = @($searchresults.Properties.dnsroot)
$netbiosDomains = @($searchresults.Properties.netbiosname)`

**Comment by adrian-moore** [comment]
Cheers, Russel.

Do you want to raise a PR with the above code? Or would you rather we take care of it?

Adrian

**Comment by davefalkus** [comment]
@russelltomkins please send a PR to update the script.

Thanks

Dave
