### ISSUE TITLE
Function Application_iOS_Add updates needed

### ISSUE THREAD

**Issue by Mal-G** [microsoftgraph/powershell-intune-samples#116]
Hello,
A couple of things...
Function Application_iOS_Add has wrong Header Example information/comment. Looks like it was borrowed from Get-AuthToken and not updated. 
Also, and more importantly, the function needs updating to increase it's support for more possible supported OS versions, up to iOS 12 and soon 13. e.g.
From..
            minimumSupportedOperatingSystem=@{
                v8_0=$osVersion -lt 9.0;
                v9_0=$osVersion -eq 9.0;
                v10_0=$osVersion -gt 9.0;
            };

To. something like...
            minimumSupportedOperatingSystem=@{
                v8_0=$osVersion -lt 9.0;
                v9_0=$osVersion -eq 9.0;
                v10_0=$osVersion -eq 10.0;
                v11_0=$osVersion -eq 11.0;
                v12_0=$osVersion -ge 12.0;
            };
However, even than i'm not sure the code would handle minor point OS versions of say "11.1" - which is a valid value for $osVersion, even after the 'split' to ensure one decimal place.  I think we'd need code similar to "v11_0=$($osVersion -like '11.*')" etc.

**Comment by davefalkus** [comment]
Hi @Mal-G,

Fixed the issue with an update to the sample script. Script will look for minimumOsVersion by startswith.

https://github.com/microsoftgraph/powershell-intune-samples/blob/master/Applications/Application_iOS_Add.ps1

Thanks for finding it.

Dave
