### ISSUE TITLE
Error in Patch : Update iosManagedAppProtection

### ISSUE THREAD

**Issue by kpandeyMRE** [microsoftgraph/powershell-intune-samples#117]
Hi Team,
I am getting error while doing PATCH operation iosManagedAppProtection policy.
Error : 
"code": "ModelValidationFailure",
 "message": "Cannot apply PATCH to navigation property 'apps' on entity type 'microsoft.management.services.api.iosManagedAppProtec
tion'

Does this PATCH request works for AppProtection policies? Although I couldn't find sample for this API in your sample code.
In both the API version (beta/v1.0) this says that it should work.
PATCH /deviceAppManagement/iosManagedAppProtections/{iosManagedAppProtectionId}
Thanks.

**Comment by davefalkus** [comment]
Hi @kpandeyMRE,

To patch an iOS App Protection Policy you can use the following URI with your ID ("iosManagedAppProtectionId") of your policy. The notable difference is that the ID is in brackets versus the / then ID.

PATCH /deviceAppManagement/iosManagedAppProtections('iosManagedAppProtectionId')

Example JSON Content:
{
     "allowedOutboundDataTransferDestinations":"managedApps",
     "@odata.type":"#microsoft.graph.iosManagedAppProtection"
}

I will provide feedback to team on the document which your referencing.
https://docs.microsoft.com/en-us/graph/api/intune-shared-iosmanagedappprotection-update?view=graph-rest-beta

Dave

**Comment by MclMax1** [comment]
Hi @davefalkus 
Can you please explain the workaround again?
I think the error is still there and not updated in the documentation yet. 
"error": {
    "code": "ModelValidationFailure",
    "message": "Cannot apply PATCH to navigation property 'apps' on entity type 'microsoft.management.services.api.iosManagedAppProtection'.",
    "innerError": {
      "message": "Cannot apply PATCH to navigation property 'apps' on entity type 'microsoft.management.services.api.iosManagedAppProtection'.",
      "date": "2021-03-22T13:10:08",

Also tried MS Graph Requests an none worked:
https://graph.microsoft.com/beta/deviceAppManagement/iosManagedAppProtections/id
https://graph.microsoft.com/beta/deviceAppManagement/iosManagedAppProtections/(id)
https://graph.microsoft.com/beta/deviceAppManagement/iosManagedAppProtectionsid 
https://graph.microsoft.com/beta/deviceAppManagement/iosManagedAppProtections(id)

Do you have any workaroung for us?
