### ISSUE TITLE
ICCID returns null

### ISSUE THREAD

**Issue by nowiresmatt** [microsoftgraph/powershell-intune-samples#118]
Changing the graph API version to "beta" this returns all ICCID values as null.

This may be a graph api problem - a specific device query with a select of iccid will return the ICCID but a query over multiple devices or all fields will return null.
eg...
https://graph.microsoft.com/beta/devicemanagement/manageddevices/{cccccccc}/?select=iccid
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#deviceManagement/managedDevices(iccid)/$entity",
    "iccid": "8xxxxxxxx3016456"
}

vs
https://graph.microsoft.com/beta/devicemanagement/manageddevices/{jklsldkfnlskndfmc}/

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#deviceManagement/managedDevices/$entity",
    "id": "jklsldkfnlskndfmc",
…….
    "iccid": "",
    "udid": "",

**Comment by davefalkus** [comment]
Hi @nowiresmatt 

The ICCID is returned at the individual device level, not at the top level "deviceManagement/managedDevices" as you've found. If you want the ICCID you have to query the device itself.

https://graph.microsoft.com/beta/deviceManagement/managedDevices/17f71011-fea7-49b3-9908-f841f48e0c79?$select=iccid

For multiple devices you will have to loop through them.

Dave
