### ISSUE TITLE
Applications\Application_iOS_Add.ps1 fails

### ISSUE THREAD

**Issue by JankeSkanke** [microsoftgraph/powershell-intune-samples#12]
Publishing Microsoft Outlook - email and calendar

You cannot call a method on a null-valued expression.
At C:\Temp\IntunePS\powershell-intune-samples-master\Applications\Application_iOS_Add.ps1:340 char:5
+     $errorResponse = $ex.Response.GetResponseStream()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by davefalkus** [comment]
Hi JankeSkanke,

I'm currently looking into it, it looks like there is an invalid character in the script, so I will upload it again.

Thanks

Dave

**Comment by JankeSkanke** [comment]
I have gone through the script in visual studio code and removed all invalid characters, still having the same error.

**Comment by davefalkus** [comment]
Looking at it now, should have a fix shortly.

**Comment by davefalkus** [comment]
Hi JankeSkanke,

I've just updated the add iOS application script with updated description replace as it has UTF8 characters which powershell didn't like.

$app.description -replace "[^\x00-\x7F]+",""

Could you test and confirm its working then I will update the other script.

Thanks

Dave

**Comment by JankeSkanke** [comment]
Tested your latest version and no more invalid characters. But my script still fails. 
1. The 60x60 artworkurl has a typo as it says artworkurk
2. The adding of app failes with the below message.
---------------------------------------------------
Publishing Microsoft OneDrive
60x60 icon not found, using 100x100 icon
You cannot call a method on a null-valued expression.
At C:\Users\JanKetilSkanke\Documents\GitHub\powershell-intune-samples\Applications\Application_iOS_Add.ps1:339 char:5
+     $errorResponse = $ex.Response.GetResponseStream()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

I have tried to look further with visual studio code to find out what happens, and the exception gives me this: "Exception calling "ToDouble" with "1" argument(s): "Input string was not in a correct format."" 
It looks for me that the line   $osVersion = [Convert]::ToDouble($app.minimumOsVersion) is creating the error on line 292

**Comment by davefalkus** [comment]
Hi JankeSkanke,

I've tested the script specifically with Microsoft OneDrive and it doesn't fail for me.

Could you output the value to host so I can see what your getting and reply to this thread:

Write-host $app.minimumOsVersion -ForegroundColor Cyan
Write-host $app.minimumOsVersion.gettype() -ForegroundColor Cyan

Thanks

Dave

**Comment by JankeSkanke** [comment]
Publishing Microsoft OneDrive
9.0
System.String
Request to https://graph.microsoft.com/Beta/deviceAppManagement/mobileApps failed with HTTP Status 0
You cannot call a method on a null-valued expression.
At C:\Users\JanKetilSkanke\Documents\GitHub\powershell-intune-samples\Applications\Application_iOS_Add.ps1:347 char:9
         $errorResponse = $ex.Response.GetResponseStream()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : InvalidOperation: (:) [], RuntimeException
     FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by JankeSkanke** [comment]
Working as expected for me now on latest tests.

**Comment by Mr-Tbone** [comment]
Had the same problem!
Spent hours trying to find a solution.
Found out that I had SV-SE regional settings and if I changed to EN-US the script worked.
I Have now sugested a change for this script to change culture in script to EN-US.

# Add this to the start of the script
# Set parameter for culture for script execution
$culture = "EN-US"
# Backup current culture
$OldCulture = [System.Threading.Thread]::CurrentThread.CurrentCulture
$OldUICulture = [System.Threading.Thread]::CurrentThread.CurrentUICulture
# Set new Culture for script execution 
[System.Threading.Thread]::CurrentThread.CurrentCulture = $culture
[System.Threading.Thread]::CurrentThread.CurrentUICulture = $culture

#Add this to the end of the script
#Restore culture from backup
[System.Threading.Thread]::CurrentThread.CurrentCulture = $OldCulture
[System.Threading.Thread]::CurrentThread.CurrentUICulture = $OldUICulture
