### ISSUE TITLE
Use SPN to get /intuneBrandingProfiles result in (401) Unauthorized. 

### ISSUE THREAD

**Issue by AtleVa** [microsoftgraph/powershell-intune-samples#121]
Have created a SPN with permission to rest api for  devicemanagment. I am using powershell and are able to get and update "deviceconfiguration", but trying to list intunebrandingprofiles result in Unauthorized. Have given the SPN  "DeviceManagementApps.ReadWrite.All" .  Endpoint : "https://graph.microsoft.com/beta/deviceManagement/intuneBrandingProfiles". 
Also the tenant has Intune licenses , but also Microsofft 365 E3.
Kind regards AV

**Comment by Yomodo** [comment]
Today, 1 year later, I have, almost, the same: Forbidden

**Comment by davefalkus** [comment]
This is has been closed for housekeeping, please re-open if issue still exists
