### ISSUE TITLE
Win32_Application_Add.ps1 / Upload-Win32Lob not working anymore

### ISSUE THREAD

**Issue by serial666** [microsoftgraph/powershell-intune-samples#123]
I just tried to create a new Win32 app on my tenant but then I get an error 400 bad request back, did something change in the backend which is causing this problem? Do I need to add more required fields to the JSON which are missing from Win32_Application_Add.ps1?

Import-Module "C:\tmp\Win32_Application_Add.ps1" -force
$SourceFile = "C:\tmp\Deploy-Application.intunewin"
$DetectionXML = Get-IntuneWinXML "$SourceFile" -fileName "detection.xml"
$DetectionRule = New-DetectionRule -MSI -MSIproductCode "{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}"
$ReturnCodes = Get-DefaultReturnCodes

Upload-Win32Lob -SourceFile "$SourceFile" -displayName "TestTestTest" -publisher "TestTestTest" -description "TestTestTest" -detectionRules $DetectionRule -returnCodes $ReturnCodes -installCmdLine "Deploy-Application.exe" -uninstallCmdLine "Deploy-Application.exe Uninstall"

This is the actual output of "Upload-Win32Lob":

Testing if SourceFile 'C:\tmp\Deploy-Application.intunewin' Path is valid...

Creating JSON data to pass to the service...

Creating application in Intune...
POST https://graph.microsoft.com/beta/deviceAppManagement/mobileApps
{
    "msiInformation":  null,
    "description":  "TestTestTest",
    "displayName":  "TestTestTest",
    "minimumSupportedOperatingSystem":  {
                                            "v10_1607":  true
                                        },
    "fileName":  "Deploy-Application.intunewin",
    "@odata.type":  "#microsoft.graph.win32LobApp",
    "privacyInformationUrl":  null,
    "notes":  "",
    "informationUrl":  null,
    "installExperience":  {
                              "runAsAccount":  "system"
                          },
    "installCommandLine":  "Deploy-Application.exe",
    "publisher":  "TestTestTest",
    "runAs32bit":  false,
    "uninstallCommandLine":  "Deploy-Application.exe Uninstall",
    "owner":  "",
    "setupFilePath":  "Deploy-Application.exe",
    "developer":  "",
    "isFeatured":  false,
    "detectionRules":  {
                           "productVersion":  null,
                           "productCode":  "{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}",
                           "productVersionOperator":  "notConfigured",
                           "@odata.type":  "#microsoft.graph.win32LobAppProductCodeDetection"
                       },
    "returnCodes":  [
                        {
                            "returnCode":  0,
                            "type":  "success"
                        },
                        {
                            "returnCode":  1707,
                            "type":  "success"
                        },
                        {
                            "returnCode":  3010,
                            "type":  "softReboot"
                        },
                        {
                            "returnCode":  1641,
                            "type":  "hardReboot"
                        },
                        {
                            "returnCode":  1618,
                            "type":  "retry"
                        }
                    ]
}

POST https://graph.microsoft.com/beta/deviceAppManagement/mobileApps
The remote server returned an error: (400) Bad Request.

Aborting with exception: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()

**Comment by davefalkus** [comment]
Hi @serial666 ,

If you change your code to the below it works:

$MSIRule = New-DetectionRule -MSI -MSIproductCode "{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}"

$DetectionRule = @($MSIRule)

Let me know if it doesn't.

Dave

**Comment by serial666** [comment]
Hi davefalkus@,

I really missed the fact that the detection rule should have been sent as an array instead, it works now!!!

Thank you very much for your clue bat stick! Case can be closed!

/Ricardo
