### ISSUE TITLE
SoftwareUpdates_Import_FromJSON - Error

### ISSUE THREAD

**Issue by mscloudbb01** [microsoftgraph/powershell-intune-samples#125]
Hi Guys,

Appears to be an issue with the script for the "SoftwareUpdates_Import_FromJSON".

I've attached the output from when running the script.

Any ideas would be appreciated.

Thanks
[Script_Error.txt](https://github.com/microsoftgraph/powershell-intune-samples/files/4225985/Script_Error.txt)

**Comment by davefalkus** [comment]
Hi @mscloudbb01,

Fixed issue with update to sample script to remove property supportsScopeTags. 
https://github.com/microsoftgraph/powershell-intune-samples/blob/master/SoftwareUpdates/SoftwareUpdates_Import_FromJSON.ps1

Complete and tested.

Thanks

Dave
