### ISSUE TITLE
Application access vs Delegated access

### ISSUE THREAD

**Issue by bobakmansouri** [microsoftgraph/powershell-intune-samples#129]
I have been using the Intune Managed Devices and compliance policies scripts for a while using delegated access but after the application access was introduced I cannot find any of the scripts working with just the application id and secret. Any of these samples are rewritten for "application access" or any samples for me to make it work? I need to run these unattended using application access.

**Comment by davefalkus** [comment]
Hi @bobakmansouri,

I've just added a sample script for Application authentication, please review graph documentation listed in the readme for setting it up.

https://github.com/microsoftgraph/powershell-intune-samples/blob/master/Authentication/Auth_AppOnly.ps1

Thanks

Dave
