### ISSUE TITLE
Reset passcode

### ISSUE THREAD

**Issue by cvanaxel** [microsoftgraph/powershell-intune-samples#13]
If you Reset the passcode. How can you see the new passcode?

**Comment by davefalkus** [comment]
Hi Cvanaxel,

Apologies for the late reply on this, which version of Android are you testing against? With android 7.0 the resetpasscode is no longer available.

If you use the script the resetPasscode will show in the Devices node - Manage All Devices - then select your device and it will show the temporary password.

Thanks

Dave

**Comment by cvanaxel** [comment]
I'n using windows phone. My question was more. Is there no way to get the reset pass in powershella

**Comment by davefalkus** [comment]
We have resetPasscode action result but its not been implemented in the sample.

https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/intune_onboarding_resetpasscodeactionresult

**Comment by davefalkus** [comment]
If you select the device and get the device ID you can run the following to return the resetPasscode:

$uri = "https://graph.microsoft.com/beta/manageddevices('$DeviceID')?`$select=deviceActionResults"
(Invoke-RestMethod -Uri $uri –Headers $authToken –Method Get).deviceActionResults

**Comment by davefalkus** [comment]
Hi cvanaxel,

Did the above resolve your issue?

Thanks

Dave
