### ISSUE TITLE
Question: MacOS equivalent of Upload LOB Application

### ISSUE THREAD

**Issue by nareshbhatia** [microsoftgraph/powershell-intune-samples#133]
Hi Microsoft Graph Team,

I am trying to automate my CI/CD pipeline that builds an iOS LOB application. The build runs on a Mac (there is not other option to build an iOS app). Is there an equivalent of the Poweshell 'Upload LOB Application" for MacOS (bash, zsh, or equivalent) that will allow me to upload the app to Intune?

In fact, I am trying to do something simpler that the Powershell example - the creation of the iOS LOB app has been already done manually in Intune. I even have an application id for it. All I need to do is to upload newer versions form the build pipeline and bump up version numbers.

Looking forward to your guidance.

**Comment by nareshbhatia** [comment]
Hi Microsoft Graph team, I realize that this issue is not directly related to PowerShell, however any reference to similar work on MacOS would be greatly appreciated.

TIA

**Comment by davefalkus** [comment]
Hi @nareshbhatia,

As you suggested this repository is for PowerShell sample scripts. We had from another issue using a preview of .Net 2.0 to authenticate on MacOS, after that the code should be the same if .Net 2.0 supports the same functions. 

https://github.com/microsoft/Intune-PowerShell-SDK/releases/tag/Preview3-netstandard2.0

1. Grab the preview of netstandard2 (https://github.com/microsoft/Intune-PowerShell-SDK/releases/tag/Preview3-netstandard2.0)
2. in that package navigate to the ./release/netstandard2.0 direcctory
3. from pwsh prompt run import-module ./microsoft.graph.intune.psd1

Thanks

Dave
