### ISSUE TITLE
$OnboardingXMLFile issue with MacOS_MDATP_Deployment_Add.ps1

### ISSUE THREAD

**Issue by richlilly2004** [microsoftgraph/powershell-intune-samples#135]
Running the script outright causes $OnboardingXML to be empty and not populate the policy properly

**Comment by davefalkus** [comment]
Hi @richlilly2004 

Can you expand on what you've found here?

Thanks

Dave

**Comment by richlilly2004** [comment]
Sure, when I drop my xml path in, for instance:
C:\VMs\WindowsDefenderATPOnboarding.xml

The script runs, but ends up populating nothing in the onboarding policy. Tracing it back, I didn't get a failure on the file path or anything else, however, when I run:
$OnboardingXMLFile = get-content "$OnboardingXMLFilePath" -Encoding byte
$OnboardingXML = [System.Convert]::ToBase64String($OnboardingXMLFile)

I do get the Base64 String just fine.

**Comment by davefalkus** [comment]
Should be fixed now @richlilly2004 , let me know if it isn't

Dave

**Comment by richlilly2004** [comment]
All good now, thanks!
