### ISSUE TITLE
Out-File not working

### ISSUE THREAD

**Issue by scerazy** [microsoftgraph/powershell-intune-samples#137]
Needed to get output to a file for Win10_PrimaryUser_Get.ps1
| out-file
created empty 0k file

Had to resort to:
Start-Transcript $File -Append
.
Stop-Transcript

Any ideas?

**Comment by davefalkus** [comment]
Hi @scerazy,

To use out-file for that script, the script would need changing so the output i.e. write-host elements are written to an array / object. Once all are in an array you can out-file the results.

Dave

**Comment by scerazy** [comment]
Pity, too much trouble

**Comment by jonwbstr** [comment]
Start-transcript? Not pretty, bit it would work.

**Comment by scerazy** [comment]
It does (not would) work
