### ISSUE TITLE
Authenticate as computer to Azure resources

### ISSUE THREAD

**Issue by kenjohnson03** [microsoftgraph/powershell-intune-samples#139]
Do we have an example for authenticating as the computer to an Azure resource? For instance sending a JSON file to Azure Storage (blog or table). Or, authenticating to an Azure Function as computer to pull a Shared Access key for secure transmission of secrets?

**Comment by davefalkus** [comment]
Hi @kenjohnson03,

This repository doesn't have a sample for what your asking, this repo is purely for PowerShell Intune sample scripts.

Thanks

Dave
