### ISSUE TITLE
Android import error - failed with HTTP 

### ISSUE THREAD

**Issue by micasa001** [microsoftgraph/powershell-intune-samples#144]
The import for applications is giving all errors when you try to import Android Apps. All other scripts and JSON import/exports are working find but this isnt. You know if there is a fix for this?

MDM Application ‘Managed Home Screen’
Response content:
{
“error”: {
“code”: “BadRequest”,
“message”: “{\r\n \”_version\”: 3,\r\n \”Message\”: \”An error has occurred – Operation ID (for customer support): 00000000-0000-0000-0000-0000000
00000 – Activity ID: f84c8843-e294-4d09-8a1c-4b5751d61e94 – Url: https://fef.amsub0502.manage.microsoft.com/AppLifecycle_2007/StatelessAppMetadataFEServ
ice/deviceAppManagement/mobileApps?api-version=5020-06-22\”,\r\n \”CustomApiErrorPhrase\”: \”\”,\r\n \”RetryAfter\”: null,\r\n \”ErrorSourceService\”
: \”\”,\r\n \”HttpHeaders\”: \”{}\”\r\n}”,
“innerError”: {
“date”: “2020-08-08T22:08:27”,
“request-id”: “f84c8843-e294-4d09-8a1c-4b5751d61e94”
}
}
}
Add-MDMApplication : Request to https://graph.microsoft.com/Beta/deviceAppManagement/mobileApps failed with HTTP Status BadRequest Bad Request
At C:\PowerShell\intunetooling\Import-Applications.ps1:357 char:1
+ Add-MDMApplication -JSON $JSON_Output
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Add-MDMApplication

**Comment by davefalkus** [comment]
Hi @micasa001,

Is "Managed Home Screen" a Google Play app or Managed Google Play app?

Do you have the JSON thats failing?

Dave

**Comment by davefalkus** [comment]
Can't reproduce error, please reopen issue if its still occuring.

Dave
