### ISSUE TITLE
Unable to use samples with macOS

### ISSUE THREAD

**Issue by scheblein** [microsoftgraph/powershell-intune-samples#146]
I've successfully installed powershell 7 on macOS Catalina 10.15.6 using homebrew - _brew cask install powershell_ from https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos.

I'm successfully able to install the AzureAD module - using _Install-Module -Name AzureAD_.

I'm unable to import the **AzureAD module** in order to run these samples:

PS /Users/thinkmac> Import-Module -Name AzureAD
Import-Module: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

**Comment by davefalkus** [comment]
These sample scripts are only tested on Windows 10.

Will do some research on future possibilities, also please review link below which states Azure modules are not .Net Core compatible.
https://github.com/PowerShell/PowerShell/issues/11812

https://azure.microsoft.com/es-es/blog/azure-powershell-cross-platform-az-module-replacing-azurerm/
