### ISSUE TITLE
Get-RBACScopeTag -DisplayName not working

### ISSUE THREAD

**Issue by archeedev** [microsoftgraph/powershell-intune-samples#147]
In Intune I have ScopeTag : Lenovo

Get-RBACScopeTag - will return all the tags alright
however
Get-RBACScopeTag -DisplayName "Lenovo" - returns nothing

Similar REST query, eg. from RBAC_ScopeTags_DeviceAssign.ps1, for managed device works fine but not this one.

My goal: retrieve scope tag Id by it's DisplayName

**Comment by davefalkus** [comment]
Hi @archeedev,

Which script are you using where Get-RBACScopeTag -DisplayName "Lenovo" fails?

Dave

**Comment by archeedev** [comment]
hi, I was using content of RBAC_ScopeTags_DeviceAssign.ps1
I must have been doing something wrong. 
Checked again now and all works fine - ok to close this thread.
