### ISSUE TITLE
Unable to authenticate on MacOS - PowerShell Core 7.0

### ISSUE THREAD

**Issue by efie45** [microsoftgraph/powershell-intune-samples#148]
Neither -AdminConsent or -PSCredential parameters work on MacOS with PowerShell v7 installed. This is the error:
Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral

**Comment by kevsully** [comment]
Hi Ethan, I just went through this to confirm and there are some things you may need to do that are preview so support may vary, but it is working for me. 

So;

1. Grab the preview of netstandard2 (https://github.com/microsoft/Intune-PowerShell-SDK/releases/tag/Preview3-netstandard2.0)
2. in that package navigate to the ./release/netstandard2.0 direcctory
3. from pwsh prompt run import-module ./microsoft.graph.intune.psd1

That pointed me to microsoft.com/devicelogin to get signed in and it worked fine... without this updated .net it won't authenticate and throw the error you have above...
