### ISSUE TITLE
ManagedDevices_Get.ps1  Error

### ISSUE THREAD

**Issue by Ahigu** [microsoftgraph/powershell-intune-samples#15]
I get the following error trying to run ManagedDevices_Get.ps1 

PS C:\Windows\system32> C:\scripts\Getintunedevices.ps1

Please specify your user principal name for Azure Authentication: adrian.higuero
s@autismspeaks.org

Checking for AzureAD module...
Cannot find an overload for "AcquireTokenAsync" and the argument count: "5".

PS C:\Windows\system32>

Can anyone help?

**Comment by davefalkus** [comment]
Hi Ahigu,

Are you using the Azure Active Directory Module for Windows Powershell shortcut to test the script? If so could you run a native Powershell window without loading the MSOnline module and it should work.

Let me know if it doesn't.

Dave

**Comment by Ahigu** [comment]
Dave,
I ran it from a normal powershell window and I got the following:

Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

PS C:\windows\System32> C:\Scripts\Getintunedevices.ps1

Please specify your user principal name for Azure Authentication: adrian.higueros@autismspeaks.org

Checking for AzureAD module...
WARNING: EAS Devices are excluded by default, please use -IncludeEAS if you want to include those devices

You cannot call a method on a null-valued expression.
At C:\Scripts\Getintunedevices.ps1:222 char:5
+     $errorResponse = $ex.Response.GetResponseStream()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull


No Managed Devices found...

PS C:\windows\System32>

**Comment by davefalkus** [comment]
Hi Ahigu,

I've just updated the script as there was some invalid characters from the upload, could you test it again and let me know the result. I've tested from my side and the script is working.

Thanks

Dave

**Comment by Ahigu** [comment]
Thanks Dave things are working as intended now. Is there a way to export this to a csv file???

**Comment by davefalkus** [comment]
The ManagedDevices_Hardware_Get.ps1 will export to a CSV:
https://github.com/microsoftgraph/powershell-intune-samples/blob/master/ManagedDevices/ManagedDevices_Hardware_Get.ps1

**Comment by davefalkus** [comment]
Hi Ahigu,

If everything is working for you I will close the issue, feel free to open the issue again if you hit any issues.

Dave

**Comment by Ahigu** [comment]
Dave,

Quick question if you don’t mind.

I want to have all mdm and eas devices reported on. When I run the ManagedIntuneDevices.pst -includeEAS I still only get the same MD devices. Do I need to change the script itself??

Adrian Higueros
Senior Network Engineer
Autism Speaks
1 East 33rd Street, 4th Floor
New York NY 10016
Phone: 646-385-8551
adrian.higueros@autismspeaks.org
<mailto:adrian.higueros@autismspeaks.org>www.autismspeaks.org<http://www.autismspeaks.org/>

[AS-Email-Walk-Banner- enhancing lives (2) (002)]
