### ISSUE TITLE
ManagedDevices_DeviceOwnership_Set.ps1 does not return all devices.

### ISSUE THREAD

**Issue by WarlockAUS** [microsoftgraph/powershell-intune-samples#152]
script output show no managed devices found Where-Object {$_.managedDeviceOwnerType -like '*personal*' -and $_.manufacturer -like '*apple*'}

However i have over 400 devices listed as personal in the intune portal.

the script will pick up one or two, never one of the current 400.

is there a specific state the device needs to be in before the code can find it?

**Comment by davefalkus** [comment]
Hi @WarlockAUS,

Could you change your query to add $_ is required e.g. $.manufacturer should be $_.manufacturer and $.managedDeviceOwnerType should be $_.managedDeviceOwnerType

Dave

**Comment by davefalkus** [comment]
Closing issue, please re-open if your still having issue querying for what you want.

Dave
