### ISSUE TITLE
Unable to add multiple groups on Add-DeviceConfigurationPolicyAssignment

### ISSUE THREAD

**Issue by SGeeves** [microsoftgraph/powershell-intune-samples#154]
On the Add-DeviceConfigurationPolicyAssignment.
You can only add a single group. For the setup's for my clients we have a few policies which have more than one group assigned.
If you duplicate the line after it has run in the script, this overwrites the existing group.

**Comment by davefalkus** [comment]
Which sample script are you referencing @SGeeves so I look at the right one?

**Comment by SGeeves** [comment]
Is it "DeviceConfiguration_Add_Assign.ps1"
Specifically the 'Add-DeviceConfigurationsPolicyAssignment' function.

**Comment by davefalkus** [comment]
Hi @SGeeves,

I've done a fix for this issue, please see update on the script below.

https://github.com/microsoftgraph/powershell-intune-samples/blob/master/DeviceConfiguration/DeviceConfiguration_Add_Assign.ps1 

I've also done a update to add assignment type so now you have to specify "AssignmentType" on the group addition.

Add-DeviceConfigurationPolicyAssignment -ConfigurationPolicyId $CreateResult_iOS.id -TargetGroupId $TargetGroupId -AssignmentType Included

I've tested the script and can now have duplicate lines on group assignment, so please test and let us know if it works for you. If it does please close the issue.

Dave
