### ISSUE TITLE
Export/ import Endpoint security policies

### ISSUE THREAD

**Issue by erik-wo** [microsoftgraph/powershell-intune-samples#156]
Is there a module to export/ import Endpoint security policies such as antivirus, firewall ASR and so fourth?

**Comment by davefalkus** [comment]
Hi @erik-wo,

There are the following sample scripts for export and import of Endpoint Security policies.

https://github.com/microsoftgraph/powershell-intune-samples/tree/master/EndpointSecurity

Thanks

Dave

**Comment by erik-wo** [comment]
Great! Thanks!
