### ISSUE TITLE
Get token for session

### ISSUE THREAD

**Issue by scerazy** [microsoftgraph/powershell-intune-samples#158]
Trying to run Win10_PrimaryUser_Set.ps1 from a batch file, but on every line I get:

Please specify your user principal name for Azure Authentication:

Is there a way to get a token that last the whole session?

**Comment by davefalkus** [comment]
As your using PowerShell already, why are you using a batch file to run the script?

Also why not put your code inside "Win10_PrimaryUser_Set.ps1" and customize for your requirements?
