### ISSUE TITLE
How to run scrip unattended?

### ISSUE THREAD

**Issue by JamieIntune** [microsoftgraph/powershell-intune-samples#159]
How would i uses this script unattended... using encrypted/stored credentials.. so i don't have to log in every time.

How to I pass credentials?

**Comment by davefalkus** [comment]
Hi @JamieIntune,

We have the following sample to auth from file which is stored locally on the machine.

https://github.com/microsoftgraph/powershell-intune-samples/blob/master/Authentication/Auth_From_File.ps1 

If this doesn't work for you, please re-open the issue.

Dave
