### ISSUE TITLE
error while trying to run MacOS_MDATP_Deployment_Add_Assign.ps1

### ISSUE THREAD

**Issue by spalnitkar** [microsoftgraph/powershell-intune-samples#160]
I am encountering an error when I try to run the above script for MacOS MDATP deployment.

The error is:
ParserError: C:\intune\MacOS_MDATP_Deployment_Add_Assign.ps1:197
Line |
 197 |  … ata-ga-click="(Logged out) Header, go to Features">Features <span cla …
     |                                                                ~
     | The '<' operator is reserved for future use.

I am using the latest Powershell (64) version 7;  according the the documentation, the first time the script is run if should prompt for credentials to log in to the tenant; however I get the above error and cannot proceed.

**Comment by davefalkus** [comment]
Hi @spalnitkar,

Can you test using powershell 5.0, the pre-reqs in the readme list PS v5.0, scripts haven't been tested with PS.

PowerShell v5.0 on Windows 10 x64 (PowerShell v4.0 is a minimum requirement for the scripts to function correctly)

Dave

**Comment by spalnitkar** [comment]
Thank you so much for the prompt response:

I tried it with powershell 5 and go the following errors:

PS C:\tools\m365\scripts\Intune\MacOS\intune> .\MacOS_MDATP_Deployment_Add.ps1 -OnboardingXMLFilePath 'C:\tools\m365\scripts\Intune\MacOS\intune\WindowsDefenderATPOnboarding.xml'
At C:\tools\m365\scripts\Intune\MacOS\intune\MacOS_MDATP_Deployment_Add.ps1:170 char:21
+                 Sign&nbsp;up
+                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a
string.
At C:\tools\m365\scripts\Intune\MacOS\intune\MacOS_MDATP_Deployment_Add.ps1:197 char:190
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\tools\m365\scripts\Intune\MacOS\intune\MacOS_MDATP_Deployment_Add.ps1:197 char:261
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a
string.
At C:\tools\m365\scripts\Intune\MacOS\intune\MacOS_MDATP_Deployment_Add.ps1:211 char:255
+ ... ogged out) Header, go to Customer stories">Customer stories <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\tools\m365\scripts\Intune\MacOS\intune\MacOS_MDATP_Deployment_Add.ps1:211 char:326
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a
string.
At C:\tools\m365\scripts\Intune\MacOS\intune\MacOS_MDATP_Deployment_Add.ps1:212 char:231
+ ... ata-ga-click="(Logged out) Header, go to Security">Security <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\tools\m365\scripts\Intune\MacOS\intune\MacOS_MDATP_Deployment_Add.ps1:212 char:302
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a
string.
At C:\tools\m365\scripts\Intune\MacOS\intune\MacOS_MDATP_Deployment_Add.ps1:235 char:222
+ ... a-click="(Logged out) Header, go to Explore">Explore GitHub <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\tools\m365\scripts\Intune\MacOS\intune\MacOS_MDATP_Deployment_Add.ps1:235 char:293
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a
string.
At C:\tools\m365\scripts\Intune\MacOS\intune\MacOS_MDATP_Deployment_Add.ps1:238 char:107
+ ...  text-normal text-mono f5 mb-2 border-lg-top pt-lg-3">Learn &amp; con ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a
string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

**Comment by davefalkus** [comment]
Hi @spalnitkar,

How are you creating the script, are you copying the raw content from github?

https://raw.githubusercontent.com/microsoftgraph/powershell-intune-samples/master/MDATP/MacOS_MDATP_Deployment_Add.ps1

Looks like your getting invalid characters on the download, so would be good to know how your getting the script locally.

Thanks

Dave

**Comment by spalnitkar** [comment]
Hi @davefalkus 

I am using Microsoft Edge and right-clicking the script name and selecting "Save Link As" to download it to my local machine.

Thanks,

Sanjay

**Comment by spalnitkar** [comment]
Hi @davefalkus,

Thank you so much for the pointer;  copying and pasting the raw content and creating the file seems to work.

Thanks,

Sanjay

**Comment by davefalkus** [comment]
If I repro the "Save Link As" then I get the HTML output

![image](https://user-images.githubusercontent.com/20442367/104054894-cdf9e880-51e5-11eb-87a2-ac8f42b9afa4.png)

Could you open the link below:
https://raw.githubusercontent.com/microsoftgraph/powershell-intune-samples/master/MDATP/MacOS_MDATP_Deployment_Add.ps1

Select All text then copy and create a ps1 script and retest?

Thanks

Dave

**Comment by spalnitkar** [comment]
@davefalkus, yes it works when I do that.  Thanks again for your prompt replies.

**Comment by davefalkus** [comment]
Thanks @spalnitkar, happy to help.

Will close the issue.

Dave
