### ISSUE TITLE
App Protection Policy Add-ManagedAppPolicy (error)

### ISSUE THREAD

**Issue by SGeeves** [microsoftgraph/powershell-intune-samples#173]
When running "Add-ManagedAppPolicy -Json $iOS" I get the error;

You cannot call a method on a null-valued expression.
At line:49 char:5
     $errorResponse = $ex.Response.GetResponseStream()
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: (:) [], RuntimeException
     FullyQualifiedErrorId : InvokeMethodOnNull

I am fully authenticated, and other cmdlets and functions are running ok, just not this one...

When using graph explorer with the same JSON code it works fine, looks like there is some error with the script on here maybe? (I'm not smart enough to troubleshoot this one i'm afraid!)

Thanks in advance for any guidance.

**Comment by davefalkus** [comment]
Hi @SGeeves,

Just tried to reproduce your error but it added the policy successfully.

Could you copy the raw code from this link and paste it into your script and test again. We've had instances where you copy the html there are invalid characters.

https://raw.githubusercontent.com/microsoftgraph/powershell-intune-samples/master/AppProtectionPolicy/ManagedAppPolicy_Add.ps1 

Thanks

Dave

**Comment by SGeeves** [comment]
Thanks @davefalkus - That worked this time, even with my own JSON.
I think I was a bit silly on my first post. It was actually the 'ManagedAppPolicy_add_Assign.ps1' which was not working for me.

**Comment by SGeeves** [comment]
@davefalkus - I copied the RAW code you sent on the link above, added it to the 'ManagedAppPolicy_Add_Assign.ps1' and that is now working for me. The assign part was all good, just the first function of 'Add-ManagedAppPolicy' was the issue.

All good now, thanks for the assistance!
