### ISSUE TITLE
Trying to run the check_lastSyncDateTime.ps1 and Check_enrolledDateTime.ps1getting an error 

### ISSUE THREAD

**Issue by da3bhayo** [microsoftgraph/powershell-intune-samples#18]
hi Guys,

When I try and run the script below I am getting the below error and idea which

- Install AzureAD module -check
- Connected to Azure AD- check
- changed directory to script location- check
- running PS session as admin\unrestricted-check

which is it not responding?

PS C:\windows\Scripts> .\powershell-intune-samples-master\checkstatus\Check_enrolledDateTime.ps1

Please specify your user principal name for Azure Authentication: ********

Checking for AzureAD module...
Checking if any Intune Managed Device Enrolled Date is within or equal to 1440 minutes...

Minutes Ago: 2017-12-12T10:44:20Z

Response content:
{
  "error": {
    "code": "UnknownError",
    "message": "{\"Message\":\"An internal server error has occurred - Operation ID (for customer support): 00000000-0000-000
0-0000-000000000000 - Activity ID: 7d5225ad-4733-4c8b-be6b-478fabb6f553 - Url: https://fef.msub03.manage.microsoft.com/Device
FE/StatelessDeviceFEService/managedDevices?api-version=5017-09-07&$filter=enrolledDateTime+ge+2017-12-12T10%3a44%3a20Z - Cust
omApiErrorPhrase: \"}",
    "innerError": {
      "request-id": "7d5225ad-4733-4c8b-be6b-478fabb6f553",
      "date": "2017-12-13T10:43:18"
    }
  }
}
C:\windows\Scripts\powershell-intune-samples-master\checkstatus\Check_enrolledDateTime.ps1 : Request to 
https://graph.microsoft.com/beta/managedDevices?$filter=enrolledDateTime ge 2017-12-12T10:44:20Z failed with HTTP Status 
InternalServerError Internal Server Error
At line:1 char:1
+ .\powershell-intune-samples-master\checkstatus\Check_enrolledDateTime ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Check_enrolledDateTime.ps1
 

PS C:\windows\Scripts> .\powershell-intune-samples-master\CheckStatus\Check_lastSyncDateTime.ps1

Checking to see if there are devices that haven't synced in the last 30 days...

Response content:
{
  "error": {
    "code": "UnknownError",
    "message": "{\"Message\":\"An internal server error has occurred - Operation ID (for customer support): 00000000-0000-000
0-0000-000000000000 - Activity ID: faadb462-62df-46ac-a4a5-28fe026bde81 - Url: https://fef.msub03.manage.microsoft.com/Device
FE/StatelessDeviceFEService/managedDevices?api-version=5017-09-07&$filter=lastSyncDateTime+ge+2017-11-13T10%3a54%3a04Z - Cust
omApiErrorPhrase: \"}",
    "innerError": {
      "request-id": "faadb462-62df-46ac-a4a5-28fe026bde81",
      "date": "2017-12-13T10:53:03"
    }
  }
}
C:\windows\Scripts\powershell-intune-samples-master\CheckStatus\Check_lastSyncDateTime.ps1 : Request to 
https://graph.microsoft.com/beta/managedDevices?$filter=lastSyncDateTime ge 2017-11-13T10:54:04Z failed with HTTP Status 
InternalServerError Internal Server Error
At line:1 char:1
+ .\powershell-intune-samples-master\CheckStatus\Check_lastSyncDateTime ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Check_lastSyncDateTime.ps1

**Comment by davefalkus** [comment]
Hi da3bhayo

I've just updated the script, could you try it again? We needed to update the resource route for managedDevices which has been done now.

Thanks

Dave

**Comment by da3bhayo** [comment]
great now working

**Comment by davefalkus** [comment]
Thanks for confirming, will close the issue.
Dave
