### ISSUE TITLE
ManagedAppPolicy_Get.ps1 Comes back with Error.

### ISSUE THREAD

**Issue by WilliamDShiell** [microsoftgraph/powershell-intune-samples#19]
Receive bad request error when running the following script.
I am able to pull the first Managed App Policy, Fails at Managed App Policy - Mobile Apps

Error Message:
Get-ManagedAppsPolicyMobileApps : Request to https://graph.microsoft.com/Beta/deviceAppManagemetn/iosManagedAppProtections('####################')/?$Expand=mobileAppIdentifierDeployments failed with HTTP Status 
BadRequest

Get-ManagedAppPolicyMobileApps -id $ManagedAppPolicy.id - ...

+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-ManagedAppPolicyMobileApps
bileApps

**Comment by davefalkus** [comment]
Thanks for finding this @WilliamDShiell I will fix it shortly.
Dave

**Comment by davefalkus** [comment]
Hi @WilliamDShiell 

I've updated the sample and have tested it our side, could you confirm that it works for you?

Thanks

Dave

**Comment by WilliamDShiell** [comment]
This is now working. Thanks for the help!

**Comment by davefalkus** [comment]
Thanks @WilliamDShiell for confirming, will close the issue.

Dave
