### ISSUE TITLE
Size limit on number of objects returned? (managed devices)

### ISSUE THREAD

**Issue by janegilring** [microsoftgraph/powershell-intune-samples#2]
There are 1173 devices in the tenant I am running ManagedDevices_Get.ps1 against, but only 1000 is returned by the script. Is there any restrictions on how many can be retrieved? If so, how can we override this to return all devices?

**Comment by lleonard-msft** [comment]
@janegilring - I'm investigating this and will let you know what I discover.

**Comment by lleonard-msft** [comment]
@janegilring - You are correct.  There's a default limit of 1000 items in the response.  You can use [parameters](https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters) to manage this, such as @odata.nextlink.

Additional samples are planned, so you may want to keep an eye out.

**Comment by janegilring** [comment]
Great, using @odata.nextlink. worked fine.
It would be nice if this could be incorporated in the samples, for example as a parameter (-All or similar).

**Comment by davefalkus** [comment]
Hi Janegilring, 

Does our new sample help with the paging?
https://github.com/microsoftgraph/powershell-intune-samples/tree/master/Paging

Let us know.

Dave

**Comment by janegilring** [comment]
Hi Dave,

Yes, they work like a charm. Thanks!

Jan
