### ISSUE TITLE
Invoke_DeviceAction_Set fails for 'retire' action

### ISSUE THREAD

**Issue by ricetristan** [microsoftgraph/powershell-intune-samples#20]
The **Invoke_DeviceAction_Set.ps1** script successfully obtains user details, as well as the list of managed devices, but fails for the 'retire' action with the following error:

"code": "BadRequest",
"message": "Resource not found for the segment 'managedDevices'.",

The credentials used for graph api authorization are a global tenant administrator, so it's doubtful that permissions are at issue here.

Thanks!
Tristan

**Comment by mihaiLucian** [comment]
Hello,

I am answering from my phone so I hope i was able to underderstand the issue and to verify the invoke device action script.
The managedDevices can now be found in  "deviceManagement/managedDevices" . I saw that this script was not updated.
You can update the script by modifying the resource under the Invoke-DeviceActions function.
$Resource = "deviceManagement/managedDevices".
Give it a try and let us know till Dave will update the script.

**Comment by davefalkus** [comment]
@ricetristan I've just updated the script as we hadn't updated the resource path, could you test it again?

@mihaiLucian thanks for spotting the path issue.

Dave

**Comment by ricetristan** [comment]
Sure enough, that new path fixed it.  Thanks for the quick response here!

**Comment by davefalkus** [comment]
Thanks for confirming, I will close the issue.
Dave
