### ISSUE TITLE
AppProtectionPolicies_Get

### ISSUE THREAD

**Issue by WilliamDShiell** [microsoftgraph/powershell-intune-samples#22]
Is there a way to export Windows 10 polices? Android and iOS work fine. Looking through the script it appears there is nothing written to pull the Win10 policies.

**Comment by davefalkus** [comment]
Hi @WilliamDShiell 

I've updated the Get script to pull Windows Information Protection policies now.

https://github.com/microsoftgraph/powershell-intune-samples/blob/master/AppProtectionPolicy/ManagedAppPolicy_Get.ps1

Could you let me know the results of testing and we can then close this issue.

Thanks

Dave

**Comment by WilliamDShiell** [comment]
Just tested, appears to be working as expected. You can close this issue.

Thank you!

**Comment by davefalkus** [comment]
Thanks @WilliamDShiell for confirming the update works and finding the issue in the first place.
