### ISSUE TITLE
ManagedDeviceOwnership_Set Not finding User's Devices

### ISSUE THREAD

**Issue by kmac2326** [microsoftgraph/powershell-intune-samples#23]
Hi,

ManagedDeviceOwnership_Set.ps1 doesn't seem to be returning any Devices.

When I run ManagedDevice_Get.ps1 I am only able to see  a handful devices even though I have 200+ that I can see in my Intune Azure Portal.

Ultimately, I was trying to troubleshoot why Invoke_DeviceAction_Set.ps1 was returning that the user I've inputted "do not have any owned devices". I've also tried inputting users that are returned when I run ManagedDevice_Get.ps1 but it still seems to have no effect.

I've also tried -IncludeEAS with no change in results.

**Comment by davefalkus** [comment]
Hi @kmac2326 

The managedDevice_Get.ps1 will return up to a 1000 devices due to Graph paging, there is a graph sample for paging to pull back more than a thousand devices.

Regarding the invoke_deviceAction_Set.ps1 script could you go to "Azure Active Directory", Users, specify the user you have specified in the script testing and then select devices on the left hand side. That will show the devices the user has registered in AAD which should be the same returned from the script.

Thanks
Dave

**Comment by kmac2326** [comment]
I see 4 devices, only 1 being compliant. Running the invoke script returns
that the user has no devices when I type his email or samaccount.

On Jan 10, 2018 12:58 PM, "davefalkus" <notifications@github.com> wrote:

Hi @kmac2326 <https://github.com/kmac2326>

The managedDevice_Get.ps1 will return up to a 1000 devices due to Graph
paging, there is a graph sample for paging to pull back more than a
thousand devices.

Regarding the invoke_deviceAction_Set.ps1 script could you go to "Azure
Active Directory", Users, specify the user you have specified in the script
testing and then select devices on the left hand side. That will show the
devices the user has registered in AAD which should be the same returned
from the script.

Thanks
Dave

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/microsoftgraph/powershell-intune-samples/issues/23#issuecomment-356734434>,
or mute the thread

**Comment by davefalkus** [comment]
Just to confirm as well in Azure Active Directory for the user devices they all have the MDM set to "Microsoft Intune"?
Also when you put in the UPN are you using user@tenant.onmicrosoft.com or user@domain.com?

Thanks

Dave

**Comment by kmac2326** [comment]
It looks to be set to None and it's grey'd out so I can't make changes... Is this because I am using the free version of MDM Intune from Office 365?

**Comment by kmac2326** [comment]
It looks to be set to None and it's grey'd out... Is this because I am
using the free version of MDM Intune from Office 365?

**Comment by davefalkus** [comment]
Hi @kmac2326 

The scripts in this repository will only work when the MDM authority is set to "Microsoft Intune" so the script returning 0 is correct. The sample is using "managedDevice" which is an Intune property so isn't aware of office 365 MDM devices.

https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/intune_devicefe_manageddevice_list

Take a look at https://support.office.com/en-us/article/choose-between-mdm-for-office-365-and-microsoft-intune-c93d9ab9-efb2-4349-9b93-30c30562ee22 to see the differences between o365 MDM and Microsoft Intune MDM.

Thanks

Dave

**Comment by kmac2326** [comment]
Ah got it. Thank you!
