### ISSUE TITLE
removing devices not synced in 30+ Check_LastsynDatetime_v2.2.ps1 script-please share

### ISSUE THREAD

**Issue by da3bhayo** [microsoftgraph/powershell-intune-samples#24]
Hi Dave,
I have been following your YouTube video where you used this script “Check_LastsynDatetime_v2.2.ps1” to check last sync date and time but was prompted to specific which management agent to check.
1.	EAS
2.	MDM
3.	EASMDM
4.	ALL
And then once the devices were found you were prompted on the next action
Waning are you sure you want to retire and delete the 3 devices? Y or N?

Can you please share the script

**Comment by davefalkus** [comment]
Hi @da3bhayo 

The lastSyncDate time script is the join of the following sample scripts.

https://github.com/microsoftgraph/powershell-intune-samples/blob/master/CheckStatus/Check_lastSyncDateTime.ps1

https://github.com/microsoftgraph/powershell-intune-samples/blob/master/ManagedDevices/Invoke_DeviceAction_Set.ps1

You could put them together to create the functionality you want.

Thanks

Dave
