### ISSUE TITLE
Application_MDM_Get.ps1 not finding groupAssignments

### ISSUE THREAD

**Issue by MortenRei** [microsoftgraph/powershell-intune-samples#25]
Hello

It seems like the Get-ApplicationAssignment function in Application_MDM_Get.ps1 is not able to find an apps GroupAssignments.

Response content:
{
  "error": {
    "code": "BadRequest",
    "message": "Resource not found for the segment 'groupAssignments'.",
    "innerError": {
      "request-id": "XXXX",
      "date": "2018-02-10T21:24:53"
    }
  }
}
Get-ApplicationAssignment : Request to https://graph.microsoft.com/Beta/deviceAppManagement/mobileApps/f75daeb6-7ddf-4ee9-bfe1-565abb9f592b/groupAssignments failed with HTTP Status Bad
Request Bad Request
At C:\GitHub\IronstoneIT\powershell-intune-samples\Applications\Application_MDM_Get.ps1:429 char:19
+ ... ssignment = Get-ApplicationAssignment -ApplicationId 'XXX...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-ApplicationAssignment

**Comment by MortenRei** [comment]
I found the fault, line 236 should be changed to;     
$Resource = "deviceAppManagement/mobileApps/$ApplicationId/assignments"

**Comment by davefalkus** [comment]
Thanks @MortenRei, updated the sample and output.
