### ISSUE TITLE
using GA_AdminConsent fails immediately and cannot sign in.

### ISSUE THREAD

**Issue by recycleleash** [microsoftgraph/powershell-intune-samples#264]
Trying to run the GA_AdminConsent_Set.ps1 fails immediately. I cannot input my credentials anywhere.

Sorry, but we’re having trouble signing you in.
AADSTS90013: Invalid input received from the user.

**Comment by triplanedave** [comment]
@recycleleash Changes were made to the script to require that you add your own ClientID on line 94.  You'll need to register a new app and assign permissions to that app in your tenant, then use the clientID for that app on line 94.  Do not use the clientID that starts with "d1dd" - that app is being retired and will stop working for authentication after April 1.  See the following page for information on registering a new app: https://learn.microsoft.com/entra/identity-platform/quickstart-register-app
