### ISSUE TITLE
DeviceConfiguration_Export.ps1 - Broken with the versions of Azure AD Preview that I have

### ISSUE THREAD

**Issue by Bartonian** [microsoftgraph/powershell-intune-samples#27]
Hi,

I'm trying the run the above script from my PC and I get the following error (note, I have changed the actual username for this post):

Please specify your user principal name for Azure Authentication: username@sceaust.onmicrosoft.com

Checking for AzureAD module...
AzureAD PowerShell module not found, looking for AzureADPreview
Cannot find an overload for "AcquireTokenAsync" and the argument count: "5".

Current installed modules:

ModuleType                 Version    Name                     
----------                       -------    ----                                
Binary                         2.0.0.154  AzureADPreview                    
Binary                         2.0.0.137  AzureADPreview           

If I know which version of the AzureADPreview this script was working with, then I can manually install that.  

Here's another listening of the installed modules that I have:

Version                    Name                                   Repository
2.0.0.155                 AzureAD                               PSGallery
2.0.0.154                 AzureADPreview                  PSGallery
1.3.0                       Avanade.AzureAD                PSGallery
1.2.2                       Avanade.AzureAD.Graph     PSGallery

The Operating system is Windows 10 Pro

**Comment by davefalkus** [comment]
Hi @Bartonian ,

When you load the script are you loading "Microsoft Azure Active Directory Module for Windows PowerShell"? I ask as when you see the error you have not finding "AcquireTokenAsync" its using ADAL v2, not ADAL v3 which the scripts requires.

Let us know.

Dave

**Comment by davefalkus** [comment]
Hi @Bartonian,

Could you confirm if your loading the "Microsoft Azure Active Directory Modules for Windows PowerShell"? If you are you need to use powershell.exe directly.

Closing the issue, please open the issue if the suggestion doesn't address your issue.

Thanks

Dave

**Comment by Bartonian** [comment]
That fixed it....Thanks
