### ISSUE TITLE
Bad character on blank lines

### ISSUE THREAD

**Issue by cooleyenet** [microsoftgraph/powershell-intune-samples#28]
There are 43 instances of `�` on the blank lines in this file, causing saving or copy/pasting from RAW to provide invalid PowerShell code.

**Comment by davefalkus** [comment]
Hi @cooleyenet , which file are you referencing?

Thanks
Dave

**Comment by cooleyenet** [comment]
Sorry @davefalkus , I assumed it referenced the file I clicked the button on.  The file is User_Policy_Report_Get.ps1

**Comment by davefalkus** [comment]
Thanks @cooleyenet just uploaded a fix for the invalid characters. Please close the issue if its resolved for you.

Thanks
Dave

**Comment by cooleyenet** [comment]
Awesome, looks good now. Thanks @davefalkus !
