### ISSUE TITLE
Error when requesting AuthToken

### ISSUE THREAD

**Issue by ssgrummons** [microsoftgraph/powershell-intune-samples#3]
Running Get-AuthToken is failing with this error:
```
PS C:\Users\SAMUELGRUMMONS>     $authResult = $authContext.AcquireTokenAsync($resourceAppIdURI,$clientId,$redirectUri,$platformParameters,$userId).Result
Cannot find an overload for "AcquireTokenAsync" and the argument count: "5".
At line:1 char:5
+     $authResult = $authContext.AcquireTokenAsync($resourceAppIdURI,$c ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

This error was also reported on StackOverload:
https://stackoverflow.com/questions/41132164/acquiretokenasync-not-found-for-auth-context-when-trying-to-get-token

**Comment by davefalkus** [comment]
Hi there,

What version of the AzureAD module do you have installed? Could you send the output of:

Get-Module azuread -ListAvailable

Thanks

DAve

**Comment by ssgrummons** [comment]
```PS C:\Users\SAMUELGRUMMONS> Get-Module azuread -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                                     
---------- -------    ----                                ----------------                                                                                                                     
Binary     2.0.0.115  AzureAD                             {Add-AzureADApplicationOwner, Get-AzureADApplication, Get-AzureADApplicationExtensionProperty, Get-AzureADApplicationOwner...}       



PS C:\Users\SAMUELGRUMMONS> Get-Module azureadpreview -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                                     
---------- -------    ----                                ----------------                                                                                                                     
Binary     2.0.0.114  AzureADPreview                      {Add-AzureADApplicationOwner, Get-AzureADApplication, Get-AzureADApplicationExtensionProperty, Get-AzureADApplicationOwner...}       
```
I have both AzureAD and AzureADPreview modules installed.

**Comment by davefalkus** [comment]
I've tried to reproduce the behaviour on my machine by installing both modules but it still works.

Do you remember what order you installed the modules i.e. AzureAD first then AzureADPreview? From a test you have to use the -allowclobber to install the modules side by side as the function names are identical.

If you uninstall both modules and install just the AzureAD module does that work?

Could you also give some more information about the operating system your using to see if we can reproduce the behaviour your seeing.

**Comment by ssgrummons** [comment]
What is weird is that it was working for me just this week, and it is working for one of my colleagues as well with his AAD account. I am the subscription owner of the tenant, on Win10 1703. I did the basics like reboot my box. I removed all my Azure accounts (Get-AzureAccount | Remove-AzureAccount -Force) and tried again with what I believe is a blank slate. No dice.

**Comment by ssgrummons** [comment]
Tried the following:
1. Uninstalled the AzureAD and AzureADPreview modules
2. Installed AzureAD Module
3. Removed my AzureAccounts
4. Logged into a tenant where I am the subscription owner (Add-AzureAccount) and tested Application_MDM_Get.ps1 and got same "AquireTokenAsync" error.
5. Logged out of that tenant and logged into another tenant where I am a global admin (Login-AzureRmAccount), still got the AquireTokenAsync when running the MDM script.
6. Logged in to the same tenant with another global admin account using Import-AzurePublishSettingsFile, and still got the same error.

Given that it is happening with two different tenants with three separate accounts (but not with other users), the issue must be client-side.

**Comment by davefalkus** [comment]
What happens if your colleague uses your machine to test the script?

Also have you tested on another machine to see if the issue reproduces?

**Comment by ssgrummons** [comment]
I tested on two Hyper-V VMs:
1. One was build 1703.  It failed with the same error.
2. The other was build 1607.  It worked.

Is there something in Build 1703 that would affect ADAL?

**Comment by davefalkus** [comment]
I've just build a 1703 Win 10 enterprise x64 machine and ran install-module AzureAD and it works as expected, which version of Windows 10 are you deploying?

**Comment by ssgrummons** [comment]
I swapped out the Microsoft.IdentityModel.Clients.ActiveDirectory assemblies from version 3.13.9 to version 3.13.8 in the AzureAD module, killed my ISE session, removed AzureADPreview, and then I got it working on build 1703.  Both on my physical box and my VM.

**Comment by davefalkus** [comment]
Thanks for the update, I will close the issue
