### ISSUE TITLE
DeviceConfiguration_Get.ps1 only returns the first 1000 devices

### ISSUE THREAD

**Issue by RickiB-DK** [microsoftgraph/powershell-intune-samples#30]
When I run the above script, I only get the first 1000 devices.

`$a = .\DeviceConfiguration_Get.ps1
$a.Count
1000`

**Comment by RickiB-DK** [comment]
Is it possible to implement paging so it returns all devices ?

**Comment by davefalkus** [comment]
Hi @RickiB-DK 

That script is for device configuration policies, do you have more than a thousand configuration policies? If your wanting to get more than a thousand managedDevices there is a sample paging script for managed devices here:
https://github.com/microsoftgraph/powershell-intune-samples/tree/master/Paging

Let me know.

Dave

**Comment by davefalkus** [comment]
Hi @RickiB-DK 

Did you get chance to look at the paging sample and whether you need to page against configuration policies?

Thanks

Dave

**Comment by davefalkus** [comment]
Thanks @RickiB-DK will fix the sample now and update the repository.

**Comment by RickiB-DK** [comment]
WOW, that was fast...

Will look at it, after dinner...

Thanks

**Comment by RickiB-DK** [comment]
Hi Dave,

After cleanup of the funny chars, and a minor change - i now have a working version of your script.

To get it working, i had to clear $DevicesNextLink
`$DevicesNextLink = $null`

Now it runs perfect every time.


`


    $DevicesResponse = (Invoke-RestMethod -Uri $uri -Headers $authToken -Method Get)
    $Devices = $DevicesResponse.value

    $DevicesNextLink = $DevicesResponse."@odata.nextLink"

        while ($DevicesNextLink -ne $null){

            $DevicesResponse = (Invoke-RestMethod -Uri $DevicesNextLink -Headers $authToken -Method Get)
            $DevicesNextLink = $null
            $DevicesNextLink = $DevicesResponse."@odata.nextLink"
            $Devices += $DevicesResponse.value

        }

    return $Devices
`

**Comment by RickiB-DK** [comment]
@davefalkus The 'funny' char seems to fit with the last update to the script ?

**Comment by davefalkus** [comment]
Hi @RickiB-DK 
I
n my local repo using multiple PowerShell editors I don't see any invalid characters, even downloading the Raw scripts from GitHub directly. We would like to get this fixed so other people don't see the same issue you are having.

Thanks

Dave

**Comment by RickiB-DK** [comment]
Hi @davefalkus 

This is what i'm seeing..

![billede](https://user-images.githubusercontent.com/37039062/38185817-345a18d4-3650-11e8-921b-4de2d24cc5ee.png)

In notepad ++, ISE and VS Code

![billede](https://user-images.githubusercontent.com/37039062/38185885-78e3e958-3650-11e8-9aa3-55f29d5c855c.png)

![billede](https://user-images.githubusercontent.com/37039062/38185970-e5879988-3650-11e8-972d-b16351ca66cc.png)


![billede](https://user-images.githubusercontent.com/37039062/38185931-b0eff2ec-3650-11e8-84de-fc7bf689fbfa.png)

![billede](https://user-images.githubusercontent.com/37039062/38186142-b770a1c4-3651-11e8-9292-cc73f05029d8.png)

All of them seems to come from the last change / update

![billede](https://user-images.githubusercontent.com/37039062/38186243-310c9da8-3652-11e8-9306-4233d31f01f2.png)


This was tested with a fresh download from git.

**Comment by davefalkus** [comment]
Hi @RickiB-DK 

I've just updated the script so those characters your seeing shouldn't be there anymore. Interesting in 3 editors I don't see the characters that you see but there is a space so have removed it. Hope the updated version works for you now.

Dave

**Comment by RickiB-DK** [comment]
Hi @davefalkus 

Looks like most of the invalid characters are gone, except for 2 lines...
![billede](https://user-images.githubusercontent.com/37039062/38254102-af521a4c-3758-11e8-9fb0-2bf264735fe1.png)

**Comment by RickiB-DK** [comment]
'CleanUp' version attached.
[ManagedDevices_Get_Paging.zip](https://github.com/microsoftgraph/powershell-intune-samples/files/1871922/ManagedDevices_Get_Paging.zip)

**Comment by davefalkus** [comment]
Hi @RickiB-DK 

Thanks for the feedback always good to hear. Hopefully the new update to GitHub fixes those invalid characters.

Dave

**Comment by RickiB-DK** [comment]
Hi @davefalkus 

Works perfect now !!

Thanks...

**Comment by ramdas75** [comment]
Hi,

I am getting the below error while executing the Get-ManagedDevices function. Tried with "ManagedDevices_Get_Paging.zip" also, resulting the same below error. Any clue please...

You cannot call a method on a null-valued expression.
At C:\PS1\ManagedDevices_Get-test.ps1:229 char:5
+     $errorResponse = $ex.Response.GetResponseStream()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
