### ISSUE TITLE
Trouble retire&delete devices from CSV file

### ISSUE THREAD

**Issue by ethereal962** [microsoftgraph/powershell-intune-samples#34]
I thought this would be pretty straight forward but I'm not very experienced with PS so hoping someone can assist. 

Goal: Read a list of device ids from CSV file and issue Intune device retire and delete commands for each device ID hopefully without having to answer YES to "Are you sure.." prompt for each device. 

$DeviceID = Import-Csv "C:temp\testremove.csv"
foreach ($DevID in $DeviceID)
{
    Invoke-DeviceAction -DeviceID $DevID -Retire 
    Invoke-DeviceAction -DeviceID $DevID -Delete
    }
    #>

**Comment by davefalkus** [comment]
Hi @ethereal962 

The samples scripts follow how the Intune UI completes the operation, so if you complete a retire from the UI a prompt will be shown to confirm the retirement.

You can review the function Invoke-DeviceAction on how this operation is completed.

Does this help?

Dave

**Comment by ethereal962** [comment]
If I understand correctly, it sounds like running these commands from PS will not be able to bypass the prompt since the prompt is in the browser UI. 

I can deal with the prompt but unfortunately the simple loop I wrote crashes the moment I input "Y" to the first prompt for the first device in the list.  Error message is below but I don't understand what it is telling much less how to do it correctly. 

Response content:
{
  "error": {
    "code": "InternalError",
    "message": "An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: f719ba6e-0c5f-4aa2-9d21-523fc797f239 - Url: https://fef.msua06
.manage.microsoft.com/DeviceFE/StatelessDeviceFEService/deviceManagement/managedDevices%28%27%40%7BDeviceID1%3D9d5aa283-07a9-48a7-bb8c-75beaa88862c%7D%27%29/microsoft.management.services.api.
retire?api-version=5018-01-31\r\n__BEGINCMEXCEPTIONMETADATA__\r\n{\r\n  \"_version\": 2,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-00
00-000000000000 - Activity ID: f719ba6e-0c5f-4aa2-9d21-523fc797f239 - Url: https://fef.msua06.manage.microsoft.com/DeviceFE/StatelessDeviceFEService/deviceManagement/managedDevices%28%27%40%7
BDeviceID1%3D9d5aa283-07a9-48a7-bb8c-75beaa88862c%7D%27%29/microsoft.management.services.api.retire?api-version=5018-01-31\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r
\n  \"ErrorSourceService\": \"\"\r\n}",
    "innerError": {
      "request-id": "f719ba6e-0c5f-4aa2-9d21-523fc797f239",
      "date": "2018-03-29T18:50:25"
    }
  }
}
Invoke-DeviceAction : Request to https://graph.microsoft.com/Beta/deviceManagement/managedDevices/@{DeviceID1=9d5aa283-07a9-48a7-bb8c-75beaa88862c}/retire failed with HTTP Status BadRequest 
Bad Request
At line:7 char:1
+ Invoke-DeviceAction -DeviceID $DeviceID1 -Retire
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-DeviceAction

**Comment by ethereal962** [comment]
Don't seem to be able to upload csv files so I just saved it as a TXT.

[testremove.txt](https://github.com/microsoftgraph/powershell-intune-samples/files/1862075/testremove.txt)

**Comment by davefalkus** [comment]
If you change your CSV content to:

Name,Id
DeviceID1,9d5aa283-07a9-48a7-bb8c-75beaa88862c

$DeviceID = Import-Csv "C:temp\testremove.csv"

foreach ($DevID in $DeviceID){

Invoke-DeviceAction -DeviceID $DevID.id -Retire
Invoke-DeviceAction -DeviceID $DevID.id -Delete

}

That should work, let us know.

**Comment by ethereal962** [comment]
It works!!!  I've tried a number of variations of what I previous wrote but incorporating your syntax (specifically the .id portion of $dev.ID) and it has worked every time!!

**Thank you very much!!!** 

Also, thank you for developing all the Intune sample scripts!! I've only gotten through a couple but I have no doubt many more will come in handy as I try to automate more of the Intune management we're doing.

**Comment by davefalkus** [comment]
Thanks for the feedback @ethereal962 , I will close the issue now.

**Comment by technicalman** [comment]
I have to do the same thing but can't see where in the script i have to add those lines.  i have a csv and need to do the same thing.
This is at the bottom of the script.  I just don't know where to plug in the import-csv code.

 Write-Host
    [int]$ans = Read-Host 'Enter Device id (Numerical value)'
    $selection = $menu.Item($ans)

        if($selection){

        $SelectedDevice = $Devices | ? { $_.deviceName -eq "$Selection" }

        $SelectedDeviceId = $SelectedDevice | select -ExpandProperty id

        write-host "User" $User.userPrincipalName "has device" $SelectedDevice.deviceName
        #Invoke-DeviceAction -DeviceID $SelectedDeviceId -RemoteLock -Verbose
        #Invoke-DeviceAction -DeviceID $SelectedDeviceId -Retire -Verbose
        #Invoke-DeviceAction -DeviceID $SelectedDeviceId -Wipe -Verbose
        #Invoke-DeviceAction -DeviceID $SelectedDeviceId -Delete -Verbose
        #Invoke-DeviceAction -DeviceID $SelectedDeviceId -Sync -Verbose
        Invoke-DeviceAction -DeviceID $Devices.id -rename -Verbose

        }

    }

    elseif($Devices.id.count -eq 1){

        write-host "User" $User.userPrincipalName "has one device" $Devices.deviceName
        #Invoke-DeviceAction -DeviceID $Devices.id -RemoteLock -Verbose
        #Invoke-DeviceAction -DeviceID $Devices.id -Retire -Verbose
        #Invoke-DeviceAction -DeviceID $Devices.id -Wipe -Verbose
        #Invoke-DeviceAction -DeviceID $Devices.id -Delete -Verbose
        #Invoke-DeviceAction -DeviceID $Devices.id -Sync -Verbose
        Invoke-DeviceAction -DeviceID $Devices.id -rename -Verbose

    }

}

else {

Write-Host
write-host "User $UPN doesn't have any owned Devices..." -f Yellow

}
