### ISSUE TITLE
Function Add-ApplicationAssignment acts as Set-

### ISSUE THREAD

**Issue by DoctorDJX** [microsoftgraph/powershell-intune-samples#36]
I'm trying to use the function to add a new assignment to an application with existing assignments. As described, I understood it to append to the existing assignments. Instead, it acts like a Set function and overwrites any previous assignments with just the new groupId passed to the function.

**Comment by davefalkus** [comment]
Hi @DoctorDJX 

The way that the UI works with assigning application i.e. the "assign" graph call is that it checks if there are any groups already assigned, if there are any groups assigned already they are added to the JSON that's posted to the service to add the new group with all existing groups. Would a sample script help here?

Thanks

Dave

**Comment by DoctorDJX** [comment]
Hi @davefalkus 

Thanks for the reply. A sample script would help immensely with getting an understanding of how to best approach this.

Thanks in advance!
DoctorDJX

**Comment by davefalkus** [comment]
Hi @DoctorDJX 

Added a sample to get an application and assign it if there are groups already assigned.
https://github.com/microsoftgraph/powershell-intune-samples/blob/master/Applications/Application_Get_Assign.ps1

If this doesn't work for you, please re-open this issue.

Thanks
Dave

**Comment by tacerus** [comment]
Thank you very much @davefalkus - this has been very helpful.
