### ISSUE TITLE
Function "DeviceConfiguration_Export.ps1" fails on output path with spaces (Even with "")

### ISSUE THREAD

**Issue by o-l-a-v** [microsoftgraph/powershell-intune-samples#39]
DeviceConfiguration_Export.ps1 does not support export path with spaces.

When you specify "C:\Path To\Folder\" the script fails:
* First by saying folder does not exist, create it for you? Y/n
* Then, fails at creating new folder
* Lastly, every policy it tries to write from Intune to output fails, says output folder does not exist.

**Comment by davefalkus** [comment]
Hi @o-l-a-v 

When you are asked for the directory input are you specifying quotes around path? I've just tested without quote and a space in the name i.e. c:\temp\test 1 and it works as expected.

Is the error your receiving "new-item : Cannot find drive. A drive with the name '"C' does not exist."

Thanks

Dave

**Comment by o-l-a-v** [comment]
The import json function supports quotes, so I used that with Export aswell. Will try again without quotes.

**Comment by davefalkus** [comment]
Hi @o-l-a-v 

Does it work without providing the quotes? If so could you close the issue.

Thanks

Dave

**Comment by o-l-a-v** [comment]
Hi

Sorry, forgot to test. Tested now, it worked.

I'd still wish for:
* Better error handling, don't continue script if path can't be found and/ or created
* Better explaination, how path should be supplied / syntax
* Syntax for Path should be equal across scripts; not using quotes on the ImportJSON script does not work.
* Using quotes for paths containing spaces is pretty common AFAIK, should be at least supported.

Should I open a requuest for that, and close this ticket? Or are these feature requests something you don't see being implemented?


- Olav

**Comment by davefalkus** [comment]
Hi @o-l-a-v 

I've updated the export script now so you can specify the directory with quotes or without quotes.

Also we've tested the import script with quotes and without quotes and both work without a sample change.

Could you test the change and confirm it works for you now. If you get an error could you provide an example of the path you are testing with.

Thanks

Dave

**Comment by o-l-a-v** [comment]
Hi Dave
I'll try and report back to you. Thanks!

- Olav

**Comment by o-l-a-v** [comment]
Hi

I've tried DeviceConfiguration_Export.ps1 and DeviceConfiguration_Import_FromJSON.ps1.
Path with spaces, tried with and without quotes. 
It works, so it seems that the issue is fixed. Thanks!
* Olav

**Comment by davefalkus** [comment]
Thanks @o-l-a-v I will close the issue.
