### ISSUE TITLE
InvokeDevicesActions example currently remote locks all devices against the provided UPN

### ISSUE THREAD

**Issue by Mahopper** [microsoftgraph/powershell-intune-samples#4]
The following snippet in the InvokeDeviceActions.ps1 script currently locks all devices for the UPN it is ran against:

Write-Host

Write-Host "Checking if the user" $User.displayName "has any devices assigned..." -ForegroundColor DarkCyan

$Devices = Get-AADUserDevices -UserID $id

####################################################

# Invoke-DeviceAction

####################################################

if($Devices){

$DeviceCount = $Devices.count

Write-Host "User has $DeviceCount devices added to Intune..."

    if($Devices.id.count -gt 1){

    write-host "Looping through devices..."

        foreach($Device in $Devices){

        write-host "User" $User.userPrincipalName "has device" $Device.deviceName

        **## Invoke-DeviceAction -DeviceID $Device.id -RemoteLock -Verbose** This should be commented out!
        #Invoke-DeviceAction -DeviceID $Device.id -Retire -Verbose

        #Invoke-DeviceAction -DeviceID $Device.id -Wipe -Verbose

        }

    }

**Comment by davefalkus** [comment]
Hi Mahopper,

Thanks for the feedback, it was left uncommented so that the sample would complete an action. I will comment it out and update it.

Dave

**Comment by davefalkus** [comment]
Commented out the line and updated repo.

**Comment by Mahopper** [comment]
Awesome, thanks Dave!
