### ISSUE TITLE
mdmAuthority

### ISSUE THREAD

**Issue by jydareau** [microsoftgraph/powershell-intune-samples#41]
Do you have a sample for setting mdmAuthority and the method to set 

I see you setting this parameter on the BRK3119

Member | Value | Description

unknown | 0 | Unknown
intune | 1 | Intune
sccm | 2 | SCCM
office365 | 3 | Office365

**Comment by davefalkus** [comment]
Hi @jydareau 

What we showed in the BRK3119 session was setting the MDM Authority to Intune if there was no MDM set already. The basis of the set is below:

$uri = "https://graph.microsoft.com/beta/organization"
$Organization = (Invoke-RestMethod -Uri $uri -Headers $authToken -Method Get).Value

$OrgId = $Organization.id

$uri = "https://graph.microsoft.com/beta/organization('$OrgId')?`$select=mobiledevicemanagementauthority"
$MDMAuthority = (Invoke-RestMethod -Uri $uri -Headers $authToken -Method Get).mobileDeviceManagementAuthority

$MDMAuthority

$uri = "https://graph.microsoft.com/beta/organization/$OrgId/setMobileDeviceManagementAuthority"
#Invoke-RestMethod -Uri $uri -Headers $authToken -Method Post -ContentType "application/json"

Does that help?

Dave

**Comment by jydareau** [comment]
Thanks dave

**Comment by jydareau** [comment]
I run 
the command line 
Dont apply MDMAuthority on a new Intune, if you have  the right command line , Thank
