### ISSUE TITLE
Question: C# equivalent of Upload LOB Application

### ISSUE THREAD

**Issue by shareonline** [microsoftgraph/powershell-intune-samples#47]
I know this is not an issue. but i have tried to port this to my C# MVC project, and can't seem to get it to work.
On the fileCommit action it returns commitFileFailed without any reasons.
Would it be possible to also create samples in C#? Can't seem to find any documentation with C# as language..

**Comment by davefalkus** [comment]
Hi @shareonline and @rodfmarin, if you use the PowerShell sample script to upload your application does it work?

**Comment by shareonline** [comment]
Yes the powershell script seems to work fine. I have tried to trace every step of the script in my project, comparing encryption, byte array's and so fourth, but i can't seem to find any differences.

I have a feeling that my problem lies in the chunk upload of the code.
in my project i have this:

                FileStream fileStream = new FileStream(TempFilePath, FileMode.Open, FileAccess.Read);
                using (fileStream)
                {

                    using (BinaryReader br = new BinaryReader(fileStream, new ASCIIEncoding()))
                    {
                        byte[] chunk;

                        chunk = br.ReadBytes(chunkSizeInBytes);
                        while (chunk.Length > 0)
                        {
                            uploadResponse = await UploadAzureStorageChunk(sasUri, id, Token, chunk);
                            chunk = br.ReadBytes(chunkSizeInBytes);
                        }
                    }
                }

in the powershell script it look like this:

	for ($chunk = 0; $chunk -lt $chunks; $chunk++)
	{
        $id = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($chunk.ToString("0000")));
		$ids += $id;

		$start = $chunk * $chunkSizeInBytes;
		$end = [Math]::Min($start + $chunkSizeInBytes - 1, $bytes.Length - 1);
		[byte[]]$body = **$bytes[$start..$end];**

        Write-Progress -Activity "Uploading File to Azure Storage" -status "Uploading chunk $cc of $chunks" `
        -percentComplete ($cc / $chunks*100)
        $cc++

        $uploadResponse = UploadAzureStorageChunk $sasUri $id $body;


	}

I'm a little confused by [byte[]]$body = **$bytes[$start..$end];** because i can't find a detailed explenation for what powershell actually does with this (although a have a pretty good idea).

@davefalkus can you help in any way, or maybe know of someone who can? It would be really nice to actually be able to upload software to intune in the different .NET projects i'm working on.

**Comment by casualsharper** [comment]
> 
> 
> Yes the powershell script seems to work fine. I have tried to trace every step of the script in my project, comparing encryption, byte array's and so fourth, but i can't seem to find any differences.
> 
> I have a feeling that my problem lies in the chunk upload of the code.
> in my project i have this:
> 
> ```
>             FileStream fileStream = new FileStream(TempFilePath, FileMode.Open, FileAccess.Read);
>             using (fileStream)
>             {
> 
>                 using (BinaryReader br = new BinaryReader(fileStream, new ASCIIEncoding()))
>                 {
>                     byte[] chunk;
> 
>                     chunk = br.ReadBytes(chunkSizeInBytes);
>                     while (chunk.Length > 0)
>                     {
>                         uploadResponse = await UploadAzureStorageChunk(sasUri, id, Token, chunk);
>                         chunk = br.ReadBytes(chunkSizeInBytes);
>                     }
>                 }
>             }
> ```
> 
> in the powershell script it look like this:
> 
> ```
> for ($chunk = 0; $chunk -lt $chunks; $chunk++)
> {
>     $id = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($chunk.ToString("0000")));
> 	$ids += $id;
> 
> 	$start = $chunk * $chunkSizeInBytes;
> 	$end = [Math]::Min($start + $chunkSizeInBytes - 1, $bytes.Length - 1);
> 	[byte[]]$body = **$bytes[$start..$end];**
> 
>     Write-Progress -Activity "Uploading File to Azure Storage" -status "Uploading chunk $cc of $chunks" `
>     -percentComplete ($cc / $chunks*100)
>     $cc++
> 
>     $uploadResponse = UploadAzureStorageChunk $sasUri $id $body;
> 
> 
> }
> ```
> 
> I'm a little confused by [byte[]]$body = **$bytes[$start..$end];** because i can't find a detailed explenation for what powershell actually does with this (although a have a pretty good idea).
> 
> The fileCommitFailed error is not really helping :)
> 
> @davefalkus can you help in any way, or maybe know of someone who can? It would be really nice to actually be able to upload software to intune in the different .NET projects i'm working on.

Hi,

Did you tried Microsoft.Azure.Storage.Blob library?

Install-Package Microsoft.Azure.Storage.Blob -Version 9.4.2 

```
With it in place try this method

        public static void UploadFileToBlob(string blobAbsoluteUri, string sourceFile)
        {
            CloudBlockBlob cloudBlockBlob = new CloudBlockBlob(new Uri(blobAbsoluteUri));

            //Needed optional parameter for Intune to process and commit file
            var bo = new BlobRequestOptions();
            bo.SingleBlobUploadThresholdInBytes = 1024 * 1024;

            cloudBlockBlob.UploadFromFile(sourceFile, options: bo);
        }
```

**Comment by davefalkus** [comment]
This repository provides samples for PowerShell sample scripts, any support for C# is extremely limited.
