### ISSUE TITLE
Cannot find an overload for "AcquireTokenAsync" and the argument count: "5".

### ISSUE THREAD

**Issue by Typod01** [microsoftgraph/powershell-intune-samples#48]
Hi,

Thanks for the script, I think this will be really helpful.  However I am getting an issue when running it.

The line in question is - $authResult = $authContext.AcquireTokenAsync($resourceAppIdURI,$clientId,$redirectUri,$platformParameters,$clientId).Result

The error I get is - Cannot find an overload for "AcquireTokenAsync" and the argument count: "5".

I am using Microsoft.IdentityModel.Clients.ActiveDirectory.dll version 3.19.

Any ideas would be really helpful.  Also do we think this script will work with an MFA enabled GA account?

Thanks

**Comment by davefalkus** [comment]
HI Typod01,

We have seen this issue before when loading the "Microsoft Azure Active Directory Module for Windows PowerShell" shortcut as that by default loads ADAL v2, so when you try and load a method that is in ADAL v3 it fails with your message.

Could you confirm which PowerShell window your loading and whether you automatically load any modules as part of your PowerShell profile.

Thanks
Dave

**Comment by Typod01** [comment]
I was originally using PowerGUI, old I know, but I just can't find anything quiet as good :)

I have also tried using VSCode and the standard PowerShell shortcut in Windows as well as ISE I get the same error with all of them.

![image](https://user-images.githubusercontent.com/10157119/42910455-86d2f048-8adf-11e8-88b1-e165fb2c7473.png)

I don't have any odd modules loaded either as far as I can see.

**Comment by davefalkus** [comment]
Hi @Typod01,

Which sample script have you been testing with so we can post an update for you to test?

Thanks

Dave

**Comment by davefalkus** [comment]
Hi @Typod01,

I've just updated that script, could you download again and give it a test for us?

Thanks

Dave

**Comment by Typod01** [comment]
That one worked a treat.  Thanks

**Comment by davefalkus** [comment]
Thanks @Typod01 for confirming it works for you.

We have a backlog item to update all samples with the updated authentication code.

Will close this issue.

Dave
