### ISSUE TITLE
Issues with Managed Devices Script

### ISSUE THREAD

**Issue by gherkes** [microsoftgraph/powershell-intune-samples#49]
We have tried using two of the scripts provided, but hit issues with both of them. Firstly, we have tried running ManagedDeviceOverview_Get.ps1 which gets to a certain point, errors and then does not continue. is there a way to get the script to continue on error? 
![image](https://user-images.githubusercontent.com/39519271/42877940-35ef0114-8a83-11e8-8edd-b329bbc2e044.png)

So we also tried ManagedDevices_Hardware_Get.ps1, but that only returns 1000 devices out of closer to 2000. Any ideas how we can export more than 1000?

**Comment by davefalkus** [comment]
Hi @gherkes 

The error your seeing is when the script checks the device and no user is associated the device so it fails on the lookup of the users.

The Managed Devices paging script below will get more than a 1000 devices.
https://github.com/microsoftgraph/powershell-intune-samples/blob/master/Paging/ManagedDevices_Get_Paging.ps1

Dave

**Comment by davefalkus** [comment]
Hi @gherkes,

What's the error you receive on the ManagedDeviceOverview_Get.ps1 script, that sample is getting the number of devices enrolled in the service, so it shouldn't fail.

Please reopen the issue if your still having issues.

Dave
