### ISSUE TITLE
Update ManagedDevices scripts to use v1.0 instead of beta

### ISSUE THREAD

**Issue by mrik23** [microsoftgraph/powershell-intune-samples#51]
The scripts provided are still using the beta endpoint of Graph API, it seems that now all endpoints for deviceManagement are available in v1.0, so it might be better to update the script to reflect that.

I guess that would make people more confident to use these scripts in production.

**Comment by davefalkus** [comment]
Hi @mrik23,

We have a backlog item to update the sample script to v1.0.

Thanks for flagging this with us. As we have it on backlog will close the issue.

Thanks

Dave
