### ISSUE TITLE
Trouble Authenticating Using Auth_From_File.ps1

### ISSUE THREAD

**Issue by WilliamDShiell** [microsoftgraph/powershell-intune-samples#53]
Keep receiving the following error code when attempting to use the solution outlined in Auth_From_File.

Error Message: Authorization Access Token is null, please re-run authentication...

**Comment by davefalkus** [comment]
Hi @WilliamDShiell,

Can you confirm a few things for us:

- If you authenticate manually via another sample script does the authentication work and not return the error Token is null?
- When authenticating is MFA used?
- The user is authorized to complete action your trying to complete, i.e. has an Intune Role or AAD Role allowed to complete Intune operations?

Thanks

Dave

**Comment by WilliamDShiell** [comment]
Hey Dave,

I think I was able to find the solution, in order to run this script I needed to first run one of the manual sample scripts to accept the permissions.

Thanks for the help!

-Will
