### ISSUE TITLE
Cannot find an overload for "AcquireTokenAsync" and the argument count: "5".

### ISSUE THREAD

**Issue by jsrice7391** [microsoftgraph/powershell-intune-samples#55]
`Cannot find an overload for "AcquireTokenAsync" and the argument count: "5".`

This occurs on my machine throughout using every script within the DeviceConfiguration, Authentication AppleEnrollment folder. I am prompted with "Please specify your user principal name for Azure Authentication:" which I would assume is the name of the account you wish to use with Microsoft Azure. (eg. name@company.com). After entering my credentials, I get the error

`Checking for AzureAD module...
Cannot find an overload for "AcquireTokenAsync" and the argument count: "5".`

Versions: 
Get-Module AzureAD => Version 2.0.1.16 
OS - Win 10.

**Comment by davefalkus** [comment]
Hi @jsrice7391, when you load PowerShell are you launching "Azure Active Directory module for Windows PowerShell"? If you are could you launch a PowerShell.exe window directly and retest. We are aware of an issue with you load ADAL v2 vs ADAL v3.
Thanks
Dave

**Comment by jsrice7391** [comment]
@davefalkus I wiped out everything within the loading profile and it worked. I specifically took out this line:
`
$cred = New-Object -TypeName System.Management.Automation.PSCredential -argumentlist $userName, $(convertto-securestring $password -asplaintext -force) 
Import-PSSession $(New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell -Authentication Basic -AllowRedirection -Credential (get-credential $cred)) -allowclobber
Connect-MsolService -Cred $cred
`

Thanks for the quick response to a great module. I look forward to contributing really soon.

**Comment by jsrice7391** [comment]
Thoughts on making this a NuGet package? I was thinking about doing that for my company so that we may be able to replicate

**Comment by davefalkus** [comment]
For the AquireTokenAsync issue you see, we have a sample on GitHub with an updated Get-AuthToken function which will work with ADAL v2 and ADAL v3, we are rolling this out to all script.
https://github.com/microsoftgraph/powershell-intune-samples/blob/master/AppProtectionPolicy/ManagedAppPolicy_Get.ps1
