### ISSUE TITLE
client id "d1ddf0e4-d672-4dae-b554-9d5bdfd93547" missing

### ISSUE THREAD

**Issue by ioanmoraru** [microsoftgraph/powershell-intune-samples#56]
Hello guys, 
On the new tenant, that has been created recently the Enterprise application called "Microsoft Intune Powershell" (with the client id "d1ddf0e4-d672-4dae-b554-9d5bdfd93547") is missing.  How can I add it or make it visible. This exists in the other tenants that I had then for a while. Or, maybe I am missing something...

![image](https://user-images.githubusercontent.com/42379039/44092636-53873bf2-9fd1-11e8-90d1-0e1a67ebe91d.png)

Thanks in advance for your help

**Comment by davefalkus** [comment]
Hi @ioanmoraru,

The "Microsoft Intune PowerShell" application will be created in Azure Enterprise Applications once a script has been ran against a tenant as a global admin. It won't be created by default.

Thanks
Dave

**Comment by ioanmoraru** [comment]
@davefalkus You are right. Problem solved. I've just run the script GA_AdminConsent_Set.ps1 and it worked perfectly fine. Thanks a lot four your help. 

Best regards,
Ioan

**Comment by davefalkus** [comment]
Thanks for confirming @ioanmoraru, I will close the issue.
Dave
