### ISSUE TITLE
Get-ManagedDevices doesnt work as expected

### ISSUE THREAD

**Issue by nernotdead** [microsoftgraph/powershell-intune-samples#58]
the function returns null result
looks if I run Invoke-RestMethod -Uri https://graph.microsoft.com/beta/deviceManagement/managedDevices -Headers $authToken -Method Get
and the function provides correct output only if use $graphApiVersion = "v1.0"

**Comment by davefalkus** [comment]
Hi @nernotdead,

If you browse to https://graph.microsoft.com/beta/deviceManagement/managedDevices in Graph Explorer do you get zero results returned? I've just tested that script against my tenant using the beta endpoint and all devices are returned correctly.

Thanks

Dave

**Comment by nernotdead** [comment]
Hello @davefalkus 
from graph explorer it works fine in v1.0 and beta
I'm not so experienced in Graph and learning it just for two days but would it be possible if there is something wrong with MS Intune powershell ent. app I use? I mean many authors recommend to publish a specific application for that

**Comment by davefalkus** [comment]
Hi @nernotdead,

Apologies for the delay on responding, if you check the Microsoft Intune PowerShell application in Azure by browsing to the following path you can see the permissions. Do you have "Read and write Microsoft Intune devices" set as a permission?

Enterprise applications - All applications - Microsoft Intune PowerShell - Permissions

If you want granular control on Azure application permissions then creating your own application in Azure is the way to complete that. For example, if you wanted Azure Sign-In events as well as Intune events via Graph you would have to create your own Azure Application to add that permission.

Finally are you using the same user account in Graph Explorer and the PowerShell samples?

Dave
