### ISSUE TITLE
Authorization Access Token is null, please re-run authentication... (MFA)

### ISSUE THREAD

**Issue by glego** [microsoftgraph/powershell-intune-samples#59]
@davefalkus, So I've seen this issue a couple of times, and somehow resolved. 

- I have MFA enabled, and it looks like it's not supported. 
- I've used [Auth_From_File.ps1](../blob/master/Authentication/Auth_From_File.ps1) as an example.

**Comment by TomaszGliwicki** [comment]
Hi @glego I have the same Issue. 

I'm trying to run Get-TokenAuth function with some actions in intune by Task Scheduler, unfortunately I dont know how saved password could be authenticated.

**Comment by glego** [comment]
@TomaszGliwicki , I think it's not supported. It says in the documentation to use a "service account" which hints it has no MFA enabled.

https://github.com/microsoftgraph/powershell-intune-samples/tree/master/Authentication#region-authentication

**Comment by TomaszGliwicki** [comment]
@glego I did scheduled a script in Task Scheduler, it works only when you use option "run script only when user is logged on" and then when you run it from Task Scheduler it works, it doesnt work when user is logged off. 

I've tried the Get-AuthToken with user and password, and i can achieve running a script on different user  but powershell has to be run with intune admin user. Quite complicated. 

I was also looking at Azure Automation.

**Comment by glego** [comment]
@TomaszGliwicki , Thanks for the tip. Will check that aswell.

**Comment by davefalkus** [comment]
Hi all,

There are a few examples available for using Azure Automation.

http://www.scconfigmgr.com/2018/02/26/getting-started-with-microsoft-intune-and-azure-automation/ 

You don't need to use an Intune Admin user, if the user has an Intune role and you have set delegated admin using the following sample then a Intune role user with the correct permissions can run scripts.

https://github.com/microsoftgraph/powershell-intune-samples/tree/master/AdminConsent

Dave

**Comment by TomaszGliwicki** [comment]
@davefalkus Thanks for tip, i'll do some research. What about using it through Task Scheduler, do you think that would be ever possible ? like post-beta or other way ? We'd like to leverage it.

**Comment by davefalkus** [comment]
@TomaszGliwicki when you create the script what account are you running the script under? i.e. "When running the task, use the following user account:"?

Also if the account does have MFA and you want non-interactive then a service account that has very limited permissions could be used, don't use a Global or Service Admin account!

**Comment by triplanedave** [comment]
Did you see this sample script: https://github.com/microsoftgraph/powershell-intune-samples/tree/master/Authentication

Dave Randall

**Comment by TomaszGliwicki** [comment]
I successfully set the task scheduler to run intune enrollment automated script. :)
