### ISSUE TITLE
User Report Error

### ISSUE THREAD

**Issue by ababinchak** [microsoftgraph/powershell-intune-samples#62]
I'm so happy to find these scripts. The ability to export and import into another tenant will be very helpful to me. It will also help us keep our baselines standards accurate. 

However, in running the user report script I've receiving an error in two places and I'm not sure what to do about it. Here is the issue.

OS: Windows
OS Version: 10.0.17134.228
EAS Activated: False
EAS DeviceId: 
AAD Registered: True
Enrollment Type: 
Management State: managed
Compliance State: noncompliant
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Users\AmyBabinchak\OneDrive\Documents\ReportpPolicyApplied.ps1:1175 char:50
+ ... cyStates = (Invoke-RestMethod -Uri $uri -Headers $authToken -Method G ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

and also here

Assigned Compliance Policies:
Response content:
{
  "error": {
    "code": "BadRequest",
    "message": "Resource not found for the segment 'groupAssignments'.",
    "innerError": {
      "request-id": "09a96327-3093-462b-9476-c715d7f6a213",
      "date": "2018-09-04T16:55:27"
    }
  }
}
Get-DeviceCompliancePolicyAssignment : Request to https://graph.microsoft.com/Beta/deviceManagement/deviceCompliancePolicies/49
3c92c4-01e9-46af-b490-5754cf5ccae7/groupAssignments failed with HTTP Status BadRequest Bad Request
At C:\Users\AmyBabinchak\OneDrive\Documents\ReportpPolicyApplied.ps1:1561 char:13
+     $DCPA = Get-DeviceCompliancePolicyAssignment -id $id
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-DeviceCompliancePolicyAssignment
 

No Device Compliance Policies Assigned

I will need some guidance on how to resolve.

**Comment by lowrey2142** [comment]
I'm getting the similar issue when trying to import Device configurations:

Add-DeviceConfigurationPolicy -JSON $JSON_Output

Adding Device Configuration Policy 'Global windows defender policy'
Response content:
{
  "error": {
    "code": "BadRequest",
    "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: fd029df8-8431-40bc-a1be-fe65b3fb4d43 - Url: https://fef.msub01.manage.microsoft.com/StatelessDeviceConfigurat
ionFEService/deviceManagement/deviceConfigurations?api-version=5018-08-01\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}",
    "innerError": {
      "request-id": "fd029df8-8431-40bc-a1be-fe65b3fb4d43",
      "date": "2018-09-04T18:58:17"
    }
  }
}
Add-DeviceConfigurationPolicy : Request to https://graph.microsoft.com/Beta/deviceManagement/deviceConfigurations failed with HTTP Status BadRequest Bad Request

**Comment by davefalkus** [comment]
Hi @ababinchak, 

I've just updated the user policy report script, could you try with the new version?

Dave

**Comment by davefalkus** [comment]
Hi @lowrey2142,

Could you share the JSON your trying to import?

Dave

**Comment by lowrey2142** [comment]
I used the Export to JSON script you created. As you can see it was earlier today.

On a side note, great work btw!

[Global bitlocker policy_04-09-2018-19-56-59.zip](https://github.com/microsoftgraph/powershell-intune-samples/files/2350126/Global.bitlocker.policy_04-09-2018-19-56-59.zip)

**Comment by davefalkus** [comment]
Hi @lowrey2142,

I've just updated the import script, should be fixed now. Let us know.

Dave

**Comment by ababinchak** [comment]
The user report now works with no errors. Thanks for the quick update on that. Another question, I'm looking for a report that will show all policies, not just compliance policies. Device configuration policies too. Do you have one of those?

**Comment by ababinchak** [comment]
Never mind. I was blind. :)  I'll close this now. Thanks again! Also if you need testers in the future I'm happy to help.
