### ISSUE TITLE
Auth_From_File.ps1 error

### ISSUE THREAD

**Issue by SIDFVAN** [microsoftgraph/powershell-intune-samples#63]
Hi , 
I get an error when using the Auth_From_File.ps1 script

Cannot convert argument "ctx", with value: "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext", for "AcquireTokenAsync" to type "Microsoft.IdentityModel.Clients.ActiveDire
ctory.AuthenticationContext": "Cannot convert the "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" value of type "Microsoft.IdentityModel.Clients.ActiveDirectory.Authen
ticationContext" to type "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext"."

**Comment by davefalkus** [comment]
Hi @SIDFVAN,

The credentials file that you created, was it done on the same machine that your running the script from?

Also if you run any sample script from GitHub manually on the machine does it work? i.e. no MFA prompt or other prompt?

Thanks

Dave
