### ISSUE TITLE
Powershell Core Compatibility

### ISSUE THREAD

**Issue by rodfmarin** [microsoftgraph/powershell-intune-samples#65]
https://github.com/microsoftgraph/powershell-intune-samples/blob/5bf2e5bc59ae1ce1b2980299dbd98aca49b6bd92/LOB_Application/Application_LOB_Add.ps1#L888

This script will work with PS Core 6.1, but when constructing this path string, you will receive an invalid path as a result of concatenating "\\" (backslash) on a *NIX like system.

Possibly using `[System.IO.Path]::PathSeparator` as a more agnostic approach might be considered?

**Comment by davefalkus** [comment]
Thanks for the comment, we are just updating this script so will put your change in.

Thanks
Dave
