### ISSUE TITLE
profile ID

### ISSUE THREAD

**Issue by phillkOCCM** [microsoftgraph/powershell-intune-samples#66]
I have a bad feeling some of this is depreceated, but mostly , in a document for setup is this:
$global:profileID - this is the GUID of your DEP profile that you have created in Intune. To get this guid, you must navigate to the Corporate Device Enrollment profile in the Intune portal, and the GUID is located at the end of the URL. Here is an example URL that shows you where the GUID is located: 
https://portal.azure.com/#blade/Microsoft_Intune_Enrollment/EditAcProfileBlade/overview/profileId/af897c67-05ac-469f-b6c1-64a9fa41eaea 

Specifically, I cannot find editacprofileblade in my tenant, & I am a global admin.
I'm specifically trying ot get this to work : 
https://blogs.technet.microsoft.com/smeems/2018/03/07/device-cleanup-with-graph-api/

I've modified it so that it authenticates as user. I know MS added some functionality to intunes, but it doesn't specifiy if their version sends a wipe, or just a retire, so I want to use the CSV function of that first.

**Comment by davefalkus** [comment]
Hi @phillkOCCM,

If your having issues with device cleanup script from TechNet blog please raise a comment on the blog site. 

For the DEP profile comment we are looking into it.

Dave
