### ISSUE TITLE
Conditionnal Access

### ISSUE THREAD

**Issue by jydareau** [microsoftgraph/powershell-intune-samples#67]
Hello

I would like  to set Conditionnal Access with Graph, i didnt find the API

Thanks for your Reply

Jean-Yves

**Comment by mrik23** [comment]
Not sure that falls under Intune anymore, and I don't think they have any public endpoint for this yet.

If you really want, depending on the use case, you might look at the internal API used in Azure AD.

**Comment by davefalkus** [comment]
Hi @jydareau ,

Apologies for the late response to this, Conditional Access is an AAD feature so you would need to ask that team.

Dave
