### ISSUE TITLE
IdentityVersion should not be used for VersionCode

### ISSUE THREAD

**Issue by rodfmarin** [microsoftgraph/powershell-intune-samples#68]
Hi, in this line:

https://github.com/microsoftgraph/powershell-intune-samples/blob/master/LOB_Application/Application_LOB_Add.ps1#L928

`$manifestXML.AndroidManifestProperties.PackageVersionCode = "$identityVersion" # 10`

PackageVersionCode should reflect as an integer; in my testing, if this field was something that resembled a string, the application would never appear on an assigned device.

**Comment by davefalkus** [comment]
Thanks for reporting this, will take a look at the sample code.
