### ISSUE TITLE
Ability to upload Win32 applications

### ISSUE THREAD

**Issue by onpremcloudguy** [microsoftgraph/powershell-intune-samples#69]
Hi guys, 
would i be able to ask for a sample code for uploading files in the new Win32 application type to the Intune tenants?
Thanks Steve

**Comment by davefalkus** [comment]
Hi @onpremcloudguy,

Win32 application feature is in preview, once its out of preview we will provide a sample.

Thanks

Dave

**Comment by nimrodlavi** [comment]
Has this feature been released? I can only see the option to upload win32 LOB apps and not Windows apps (win32)?

**Comment by onpremcloudguy** [comment]
> Has this feature been released? I can only see the option to upload win32 LOB apps and not Windows apps (win32)?

@nimrodlavi the win32 lob app is the code sample code required to programmatically upload a win32 app to intune
