### ISSUE TITLE
ManagedDevices -Retire not run

### ISSUE THREAD

**Issue by AlexandreRenoux** [microsoftgraph/powershell-intune-samples#7]
Hi,

I try to retire one device with : 

Invoke-DeviceAction -DeviceID "myid" -Retire -Verbose 

The script return : 

COMMENTAIRES : https://graph.microsoft.com/Beta/managedDevices/myid/retire
COMMENTAIRES : Sending retire command to myid
COMMENTAIRES : POST https://graph.microsoft.com/Beta/managedDevices/myid/retire with 0-byte payload
COMMENTAIRES : received 0-byte response of content type text/plain

No byte is sent nor received I do not understand. I do not understand. Can anyone help me?

**Comment by davefalkus** [comment]
Hi AlexandreRenoux,

When you send a managed device action there isn't a JSON payload sent with the request which would contain more than a 0 byte payload.

$Resource = "managedDevices/$DeviceID/retire"
$uri = "https://graph.microsoft.com/$graphApiVersion/$($resource)"
Invoke-RestMethod -Uri $uri -Headers $authToken -Method Post

Our documentation states the same for the response - HTTP/1.1 204 No Content

https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/intune_devicefe_manageddevice_retire

In regard to the device your targeting for a retire does it get retired? Also what OS is the device?

Thanks

Dave

**Comment by AlexandreRenoux** [comment]
hi, no the device does not retire with windows and android. I have the impression of having only the rights of reading except that I do not see or configure the writing.

**Comment by davefalkus** [comment]
Hi Alexandre, 

If you check "Device Actions" in the Devices node in the Azure console do you see the device your trying to retire?

Also if you do it manually in the UI, does the device retire?

Thanks

Dave
