### ISSUE TITLE
Auth from file no longer works

### ISSUE THREAD

**Issue by clickbangdead** [microsoftgraph/powershell-intune-samples#72]
The Auth from file doesn't seem to work. if I use the same script and provide credential at prompt, it works, but if I use a stored cred (from the same machine of course) it does not work. I don't get an error, the issue appears to be that the command:

$authResult = [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions]::AcquireTokenAsync($authContext, $resourceAppIdURI, $clientid, $userCredentials).Result;

Does nothing. No error, nothing. I've been messing around with this for awhile now and I can't get it to return an error, the variable just comes back null every time. I had updated my AzureAD module and I thought that was the issue, but removing and re-installing 2.0.0.131 didn't fix it.

**Comment by clickbangdead** [comment]
I do get the Authorization Access Token is null, please re-run authentication... error, just ot clarify, but I don't get an exception returned fron the command I pasted above.

**Comment by webermi** [comment]
I'm getting the same issue across multiple of my clients (Authentication Access Token is null).  Has this been confirmed?  Is there a fix in the works?  I know MS has had issues recently with MFA or region wide authentication.

**Comment by davefalkus** [comment]
Hi all, 

I've just tested with v2.0.0.131 of the AzureAD module and it worked as expected, can you confirm you have updated the script line 179 and 180 with username and path to credentials file.

$User = "serviceaccount@tenant.onmicrosoft.com"
$Password = "c:\credentials\credentials.txt"

Thanks

Dave

**Comment by webermi** [comment]
Hi Dave,
Just tried the latest Azure AD module - 2.0.2.4 - and I'm still getting the "Authorization Access Token is null, please re-run authentication..."
I did verify the lines above as you mentioned.  I've also recreated the password file many times.
Thanks.
Mike

**Comment by webermi** [comment]
Issue resolved for me in one tenant.  I had the incorrect username and password (how embarrassing).  Recommend running Fiddler with HTTPS enabled to see the response back from Microsoft.  Note that I had to disable and re-enable HTTPS to get it to decrypt correctly.  It notified me that the credentials were incorrect in the very last response.
Thanks Dave for testing.

**Comment by clickbangdead** [comment]
I'm still having this issue, I had updated to AzureAD Module 2.0.2.4 to prevent hangs in the Powershell ISE when running on windows 10 1803. Everything looks OK, if I run authentication without a stored creational (i.e., typing at the prompt) it works, but seems like the piece of code I pasted above is doing nothing now, it doesn't even error. I'm trying to move some code over to using AD based service accounts, so wondering if this is because the unattended auth goes to jump to our federation service an can't figure out what to do from there.

**Comment by webermi** [comment]
So I have a client with Okta federation and a local account does not work with the auth from file.  When using a cloud-only account, the auth from file did work fine.  Not sure if this helps.  I highly recommend getting fiddler traces going as well as testing cloud-only accounts.  In all cases, ensure Azure AD conditional access (especially MFA) is disabled as you work through troubleshooting.

**Comment by clickbangdead** [comment]
The issue we have is we have to move away from online-only accounts for "service" type accounts. So at some point I need to figure out how to auth using AD account and stored credentials. I can't really find any good reference code.

**Comment by clickbangdead** [comment]
Turns out, they changed over from ADFS to a new system in our dev environment. Our authentication engineer is looking at it now, we're going to have to build something out to get around the limitation in the new federation system.
