### ISSUE TITLE
Application_LOB_Add.ps1 Request for Win32 App

### ISSUE THREAD

**Issue by samspade21** [microsoftgraph/powershell-intune-samples#79]
I would like to request that a Win32 app support also be added to the Application_LOB_Add.ps1 powershell script.  (https://docs.microsoft.com/en-us/graph/api/intune-apps-webapp-create?view=graph-rest-beta).  Thanks so much!

**Comment by DieterHelmutGreiner** [comment]
This would be really great!

**Comment by Crucerio** [comment]
As the "Preview" tag in Azure Portal has been removed for this feature, I think it is time to add the Upload-Win32LobApp function. I can see, the urls are still calling the graph beta Api, but that refers to msi and apk, too.

**Comment by davefalkus** [comment]
Hi all,

Sample script for win32 upload now available here:
https://github.com/microsoftgraph/powershell-intune-samples/tree/master/LOB_Application

Will close this issue.

Thanks
Dave
