### ISSUE TITLE
Managed App Policy powershell script throws an error

### ISSUE THREAD

**Issue by MetalMav** [microsoftgraph/powershell-intune-samples#8]
I have been working with this script for a few days now and today it stopped functioning today
![map](https://user-images.githubusercontent.com/18332129/27703471-78d68222-5cd5-11e7-9bf0-02588ed735b7.PNG)

I downloaded a fresh zip of the master scripts and ran it an i am still getting the same error. Was there a change that would prevent this from working? Are there going to be many of these changes as i am writing a program that requires this functionality to be persistent without having to modify too greatly.

Thank You

**Comment by davefalkus** [comment]
Hi MetalMav,

We are aware of the error, will update the script shortly.

Dave

**Comment by davefalkus** [comment]
Hi MetalMav,

I've updated the ManagedAppPolicy_Get.ps1, could you test and let me know if it addresses your issue then I will close the issue.

Thanks

Dave

**Comment by MetalMav** [comment]
Yes it works, may i ask what the problem was so i can proactively update when i need to?

**Comment by MetalMav** [comment]
Nevermind, found it. Thanks

**Comment by davefalkus** [comment]
No problem, hope your like the scripts so far. As you have found we changed the resource name to the respected OS.

**Comment by MetalMav** [comment]
Anyway to add the defaultmanagedappprotection in there?

**Comment by MetalMav** [comment]
nvm it pulled it, thanks
