### ISSUE TITLE
implement paging for graph queries

### ISSUE THREAD

**Issue by pedrr** [microsoftgraph/powershell-intune-samples#81]
The queries currently do not support paging for the graph.
https://docs.microsoft.com/de-de/graph/paging.
Some customers have a large environment and the graph pages the response, so we need to capture this on

**Comment by davefalkus** [comment]
Hi @pedrr,

We have a paging example

**Comment by davefalkus** [comment]
Closing issue, please reopen if the above doesn't address your question
