### ISSUE TITLE
Get-ManagedDevices

### ISSUE THREAD

**Issue by sharepointland** [microsoftgraph/powershell-intune-samples#82]
The Get-ManagedDevices function and corresponding deviceManagement/manageddevices Graph API results always return an empty array for the roleScopeTagIds property of all devices. Can anyone explain why or better yet, how to include those values? 

If you supply the GUID for a device and call the same endpoint then the correct data is returned for the roleScopeTagIds property. Also, I get an "Invalid filter clause" error if I try to filter by the roleScopeTagIds property also.

**Comment by davefalkus** [comment]
To get roleScopeTagIds you need to specify the specific device by id e.g. https://graph.microsoft.com/beta/deviceManagement/managedDevices('id')
Its a property from within the device entry.
