### ISSUE TITLE
Adding ScopeTags to Applications

### ISSUE THREAD

**Issue by ethereal962** [microsoftgraph/powershell-intune-samples#83]
Apologies if I have overlooked this somewhere but wondering if anyone has a script to automate adding a scopetag to applications in Intune?

**Comment by davefalkus** [comment]
Hi @ethereal962, 

Working on a sample for application scope assignment.

Dave

**Comment by davefalkus** [comment]
Hi @ethereal962,

Added a sample to this repository, located here:
https://github.com/microsoftgraph/powershell-intune-samples/tree/master/RBAC 

Will close the issue.

Thanks
Dave
