### ISSUE TITLE
Get-AuthToken functions fail on PowerShell Core

### ISSUE THREAD

**Issue by corbob** [microsoftgraph/powershell-intune-samples#84]
It appears that the reliance on AzureAD Module prevents much of these samples from working on Core as the AzureAD Module relies on WinForms which are not available in Core. In the `ManagedDevices_Get.ps1` file, the line that is failing is: `$authResult = $authContext.AcquireTokenAsync($resourceAppIdURI, $clientId, $redirectUri, $platformParameters, $userId).Result` When breaking at this point and running the AcquireTokenAsync without extracting the result you get:

```powershell
[DBG]: PS C:\Users\corbob\Repos> $authContext.AcquireTokenAsync($resourceAppIdURI, $clientId, $redirectUri, $platformParameters, $userId)

Result                  :Id                      : 2
Exception               : System.AggregateException: One or more errors occurred. (Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.) ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.WebUI.AcquireAuthorizationAsync(Uri authorizationUri, Uri redirectUri, CallState callState)
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.AcquireAuthorizationAsync()
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.PreTokenRequestAsync()                             at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenCommonAsync(String resource, String clientId, Uri redirectUri, IPlatformParameters parameters, UserIdentifier userId, String extraQueryParameters, String claims)
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(String resource, String clientId, Uri redirectUri, IPlatformParameters parameters, UserIdentifier userId)

                          <---
Status                  : Faulted
IsCanceled              : FalseIsCompleted             : True
IsCompletedSuccessfully : False
CreationOptions         : None
AsyncState              :
IsFaulted               : TrueAsyncWaitHandle         : System.Threading.ManualResetEvent
CompletedSynchronously  : False
```

Are there any PowerShell samples that utilize the Graph API without the reliance on a technology that is not available in Core?

**Comment by davefalkus** [comment]
Hi @corbob,

There is the follow preview which should work, could you test?
https://github.com/Microsoft/Intune-PowerShell-SDK/releases/tag/Preview3-netstandard2.0  

Dave

**Comment by corbob** [comment]
Hi @davefalkus 

That works great in the Preview PowerShell Core (6.2), but still appears to try for Windows Forms in 6.1.3:

![image](https://user-images.githubusercontent.com/30301021/53920639-ac94a800-4022-11e9-9720-fba7acb4f38a.png)

That being said, it doesn't look like any of the samples in this repo (currently) use that module at all. I'll take a look at what I can do with that module and see if it will work better than putting something together with the samples provided here.

**Comment by tabs-not-spaces** [comment]
I have examples of unattended authentication - meaning, the request is sent to graph without prompting the end-user for credentials. This is how I get around using Posh Core for my CI/CD pipelines as interactive authentication cannot be relied on for unattended programmatic workflows. Perhaps this is of interest to you?

**Comment by mark4409** [comment]
> 
> 
> I have examples of unattended authentication - meaning, the request is sent to graph without prompting the end-user for credentials. This is how I get around using Posh Core for my CI/CD pipelines as interactive authentication cannot be relied on for unattended programmatic workflows. Perhaps this is of interest to you?

Hi, I'd be very interested in seeing those examples  please

**Comment by scerazy** [comment]
+1

**Comment by davefalkus** [comment]
These sample scripts are only tested on Windows 10 and PowerShell 5.1.

Will do some research on future possibilities, also please review link below which states Azure modules are not .Net Core compatible.
PowerShell/PowerShell#11812

https://azure.microsoft.com/es-es/blog/azure-powershell-cross-platform-az-module-replacing-azurerm/
