### ISSUE TITLE
Android Enterprise Devices not appearing in ManagedDevicesHardware-Get

### ISSUE THREAD

**Issue by thommck** [microsoftgraph/powershell-intune-samples#88]
We have over 200 Android Enterprise devices enrolled in Intune using the Dedicated Devices (Kiosk) enrollment. However, these do not appear in the ManagedDevicesHardware-Get script.

How can we get those included so we can have a full report on everything that we can see in the Intune portal?

**Comment by davefalkus** [comment]
Hi @thommck,

Updated script to gather Android Enterprise Device, please retest and close issue if successful.

Dave

**Comment by thommck** [comment]
Yep, that worked great thanks, the Android Enterprise/Android for Work devices now show up in the CSV
