### ISSUE TITLE
CompanyPortal_Set_Default.ps1 fails Internal Server Error

### ISSUE THREAD

**Issue by Skud13** [microsoftgraph/powershell-intune-samples#89]
This was previously working but now fails. Response content follows:

Response content:
{
  "error": {
    "code": "Unknown",
    "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An internal server error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-0000000000
00 - Activity ID: f89fa640-415b-444f-946d-94237acdf16d - Url: https://fef.amsub0202.manage.microsoft.com/StatelessOnboardingService/deviceManagement?api-version=5018-10-05
 - CustomApiErrorPhrase: efulPolicyService0StatefulBrandingPolicyProviderValidatePatchSet\",\r\n  \"CustomApiErrorPhrase\": \"efulPolicyService0StatefulBrandingPolicyProvi
derValidatePatchSet\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}",
    "innerError": {
      "request-id": "f89fa640-415b-444f-946d-94237acdf16d",
      "date": "2019-04-10T14:15:26"
    }
  }
}

**Comment by davefalkus** [comment]
Hi @Skud13,

We will take a look at this.

Dave

**Comment by davefalkus** [comment]
Hi @Skud13 ,

We've updated the sample script with a fix.

Please reopen this issue if it doesn't resolve your issue.

Dave

**Comment by Skud13** [comment]
Hi Dave,
I have incorporated the changes into my script and it works fine.
Is there a schematic anywhere with a diagram of all of the Intune/graph resources I can access?

Many thanks,

Alan.

**Comment by davefalkus** [comment]
Hi Alan,

You can use the Graph metadata from the link below to review graph resources for v1.0 and beta.
https://docs.microsoft.com/en-us/graph/traverse-the-graph

Dave
