### ISSUE TITLE
Reason device is Not Compliant

### ISSUE THREAD

**Issue by ethereal962** [microsoftgraph/powershell-intune-samples#95]
Hoping to save time search for something that may not exist. 

Is anyone aware of a script that will output the specific reason a device is considered Not Compliant? @davefalkus

**Comment by davefalkus** [comment]
Hi @ethereal962, 

The following script will show why a device isn't compliant:
https://github.com/microsoftgraph/powershell-intune-samples/blob/master/UserPolicyReport/User_Policy_Report_Get.ps1

The output looks like this:
![image](https://user-images.githubusercontent.com/20442367/62967361-b1932a00-be00-11e9-9c4b-05a57cd104b4.png)

Hope this helps. Will close the issue, please reopen if required.

Dave

**Comment by zakgold** [comment]
is there any way to return this information for all users & devices?
