### ISSUE TITLE
Set-ManagedDevice to change ownerType succeeds but does not change value

### ISSUE THREAD

**Issue by rbury** [microsoftgraph/powershell-intune-samples#96]
Using Set-ManagedDevice -id $Device.id -ownertype 'company' succeeds with a response code 204 but does not change the ownerType value on the device object.

This same result occurs using the graph explorer - https://graph.microsoft.com/beta/devicemanagement/managedDevices('managed-id-here')

Method: PATCH

Body:
```
{
    "ownerType":  "company"
}
```

**Comment by davefalkus** [comment]
Hi @rbury,

I've just tested this against one of our tenant and the device changed from personal to company using the same parameters:

https://graph.microsoft.com/beta/deviceManagement/managedDevices('1e6505d5-9ae8-40af-ae32-628b15b28151')

PATCH
{
"ownerType":"company"
}

What is the current ownerType before you make the change to company?

Dave

**Comment by rbury** [comment]
The current ownerType is unknown

My understanding was this should change automatically based on the fact that this is an iPad assigned through DEP, but neither is working. The value stays as unknown after completing enrolment as well as after the API call.

**Comment by davefalkus** [comment]
Hi @rbury,

If your iPad is stating unknown after enrollment I would raise a case with Microsoft support to figure out why its not changing. If you can't change a device in the UI from unknown to personal or corporate its not a graph issue, we need to figure out why its not enrolling correctly. Could you raise a support case?

Thanks
Dave

**Comment by rbury** [comment]
Thanks @davefalkus for the reply. I have deleted the device (intune & AzureAD) and re-enrolled. The ownership immediately changed to corporate and now appears to be accepting changes. I'm not sure what was happening with it, but appears to be working correctly now.
Thanks again!
